/**
 * Plain-language explanations for terms shown with an info button.
 * Short enough to read in a tooltip; the Learn section has the detail.
 */
export const GLOSSARY = {
  kundali: 'The birth chart: where the Sun, Moon and planets were, seen from the place and moment of birth, arranged in 12 houses.',
  lagna: 'The ascendant: the sign rising on the eastern horizon at birth. It is the 1st house and describes the body, temperament and direction of life.',
  rashi: 'Rashi means sign. The Moon sign (rashi) is used for transits, matching and daily predictions.',
  nakshatra: 'One of 27 lunar mansions of 13°20′ each. The Moon\'s nakshatra at birth (the birth star) starts the dasha sequence.',
  house: 'Each of the 12 houses covers an area of life, such as wealth (2nd), home (4th), partner (7th) or career (10th).',
  lord: 'The planet that rules the sign on a house. Where that lord sits shows how the house\'s matters develop.',
  dignity: 'How comfortable a planet is in its sign: exalted (strongest), own sign, friendly, neutral, enemy or debilitated (weakest).',
  exalted: 'A planet in its sign of greatest strength. It gives its results fully.',
  debilitated: 'A planet in its weakest sign. Its matters need more effort, unless the debilitation is cancelled (neecha bhanga).',
  retrograde: 'A planet that appears to move backwards from Earth. Its results often come after delay or a second attempt.',
  combust: 'A planet too close to the Sun. Its independent results are weakened.',
  vargottama: 'A planet in the same sign in the birth chart (D1) and the navamsa (D9). It is considered dependable and strong.',
  kendra: 'The angular houses 1, 4, 7 and 10: the pillars of the chart. Planets here are prominent.',
  trikona: 'The trine houses 1, 5 and 9: houses of fortune and merit.',
  dusthana: 'The difficult houses 6, 8 and 12: obstacles, sudden events and losses.',
  upachaya: 'Houses 3, 6, 10 and 11: houses of growth, where results improve with effort and time.',
  drishti: 'Aspect: the influence a planet casts on other houses. All planets aspect the 7th from them; Mars, Jupiter and Saturn have extra aspects.',
  karaka: 'Significator: a planet that naturally stands for something, such as Venus for marriage or Jupiter for children.',
  yoga: 'A specific combination of planets that the classical texts link to a result, such as wealth (dhana yoga) or status (raja yoga).',
  nabhasa: 'Nabhasa yogas are 32 overall patterns formed by how the seven planets are spread across signs and houses. They describe the general shape of a life and act throughout it, not only in a particular period.',
  raja: 'Raja yoga: a link between a lord of an angle (1, 4, 7, 10) and a lord of a trine (1, 5, 9). It points to status and recognition.',
  dhana: 'Dhana yoga: links between the lords of the wealth houses (1, 2, 5, 9, 11). It points to earning capacity.',
  mahapurusha: 'Pancha Mahapurusha yogas: Mars, Mercury, Jupiter, Venus or Saturn strong in an angle. Each gives a distinctive type of person.',
  parivartana: 'Parivartana: two planets in each other\'s signs (an exchange). Each acts as if in its own sign and links the two houses.',
  neechabhanga: 'Neecha bhanga: classical conditions that cancel a planet\'s debilitation, often turning early weakness into later strength.',
  dasha: 'A planetary period. The Vimshottari system divides a 120-year cycle among the nine planets; each period brings out what that planet promises in the chart.',
  antardasha: 'A sub-period inside a dasha. The pair (for example Saturn / Jupiter) sets the tone for a few months to a few years.',
  varga: 'Divisional charts (D1 to D60). Each divides every sign into parts to examine one area in detail, such as marriage (D9) or career (D10).',
  navamsa: 'The D9 divisional chart. It shows the inner strength of planets and is the main chart for marriage.',
  shadbala: 'Six-fold strength: a numerical measure of how strong each planet is, from position, direction, time, motion, nature and aspects. 100% means it meets the classical minimum.',
  ashtakavarga: 'A point system: each planet gives benefic points (bindus) to signs. More points in a sign mean planets crossing it give better results.',
  bindu: 'A benefic point in Ashtakavarga. Each planet\'s table has 0 to 8 per sign; 4 is average.',
  sav: 'Sarvashtakavarga: the total of all bindus in a sign, from 337 overall. 28 is average; more is stronger.',
  kakshya: 'Each sign is split into eight parts of 3°45′, each ruled by a planet or the lagna. A transiting planet does well in a part where that ruler gave a bindu.',
  gochara: 'Transits: where the planets are now, read against the birth chart, usually counted from the Moon sign.',
  vedha: 'Obstruction: a planet in a set house can block the good (or bad) result of another planet\'s transit.',
  sadesati: 'Sade Sati: Saturn\'s 7½-year passage over the 12th, 1st and 2nd signs from the natal Moon. Traditionally a period of pressure and responsibility.',
  varshaphal: 'The annual chart: a chart for the moment the Sun returns to its birth position each year. It shows the themes of that year.',
  muntha: 'A point that moves one sign a year from the birth lagna. Its house in the annual chart shows where the year\'s focus falls.',
  yearlord: 'The planet that rules the year in the annual chart: the strongest of five candidates that aspects the year\'s ascendant.',
  saham: 'Sensitive points in the annual chart, one for each matter such as work, marriage or children.',
  mudda: 'Mudda dasha: the Vimshottari periods compressed into one year, showing which planet leads each stretch of the year.',
  dwijanma: 'A year in which the birth ascendant rises again in the annual chart. Traditionally a sensitive year.',
  panchang: 'The Hindu almanac: the five limbs of the day (tithi, weekday, nakshatra, yoga and karana).',
  tithi: 'The lunar day: each 12° that the Moon moves ahead of the Sun. There are 30 in a lunar month.',
  karana: 'Half a tithi. Vishti (Bhadra) karana is avoided for auspicious work.',
  pyoga: 'Panchang yoga: one of 27 divisions of the combined motion of the Sun and Moon. A few, like Vyatipata and Vaidhriti, are avoided.',
  rahukaal: 'Rahu Kaal: a daily period of about 90 minutes traditionally avoided for starting new work.',
  choghadiya: 'The day and night each split into eight periods, rated favourable, neutral or unfavourable for beginning work.',
  hora: 'Planetary hours: each hour of the day is ruled by a planet, starting with the weekday\'s lord at sunrise.',
  abhijit: 'Abhijit muhurta: about 24 minutes either side of local noon, good for starting work when no better time is available.',
  taara: 'Taara: the count from your birth star to the day\'s star, in nine groups. Groups 3, 5 and 7 are avoided for important work.',
  gandanta: 'Junction points between water and fire signs (and between some tithis and nakshatras). Avoided for auspicious work.',
  muhurta: 'Electional astrology: choosing a good moment to begin something.',
  ashtakoota: 'The traditional eight-factor matching of two Moon charts, worth up to 36 points (gunas). 18 or more is traditionally acceptable.',
  guna: 'A point in Ashtakoota matching. The eight factors carry 1 to 8 points each, 36 in all.',
  mangal: 'Mangal (Kuja) dosha: Mars in certain houses, traditionally said to strain marriage. It is balanced when both partners have it or other malefics in the same houses.',
  naadi: 'Naadi: one of three groups of nakshatras. The same naadi for both partners loses all 8 points, with classical exceptions.',
  bhakoota: 'Bhakoota: the distance between the two Moon signs. 2/12, 5/9 and 6/8 lose the 7 points.',
  porutham: 'The South Indian matching system of ten agreements (poruthams).',
  ayanamsa: 'The offset between the tropical and sidereal zodiacs, about 24° today. Lahiri is the Indian government standard.',
  kp: 'Krishnamurti Paddhati: a system that uses house cusps and the sub-lords of nakshatras for precise timing.',
  chalit: 'Bhava Chalit: houses measured from the exact degree of the ascendant, so a planet can shift to the neighbouring house.',
  avastha: 'Planetary states such as age, alertness and mood, which colour how a planet delivers its results.',
  special: 'Sensitive points calculated from the chart, such as Indu lagna (wealth) or Arudha lagna (image).',
  arudha: 'Arudha (pada): the image of a house, found by counting from the house to its lord and the same distance again. The Arudha lagna shows how others see you.',
  sudarshan: 'Sudarshan chakra: reading the chart three times, from the lagna, the Moon and the Sun. What all three agree on is strongest.',
  yogi: 'The Yogi point and its lord bring luck; the Avayogi planet tends to block it. Both are calculated from the Sun and Moon longitudes.',
  pushkara: 'Pushkara navamsas and degrees: auspicious parts of the zodiac. A planet there gives better results than its sign alone suggests.',
  indu: 'Indu lagna: a wealth ascendant calculated from the 9th lords from the lagna and Moon. Benefics or strong planets there point to prosperity.',
  classical: 'Short summaries of what the classical texts (Parashara, Phaladeepika, Manasagari, as compiled by K.S. Charak) say about this placement. They are traditional indications, untested, and the texts themselves say never to judge from one factor.',
  lean: 'The overall reading of the classical rules for this area: mostly supportive, mixed or more challenging, from how many rules point each way.',
} as const

export type GlossaryKey = keyof typeof GLOSSARY
