import { useMemo } from 'react'
import { Link } from 'react-router-dom'
import { DateTime } from 'luxon'
import { computeChart } from '../astro/ephemeris'
import ChartWheel from '../components/ChartWheel'
import { SIGNS } from '../astro/constants'

export default function HomePage() {
  const now = useMemo(() => {
    const dt = DateTime.now().setZone('Europe/London')
    return computeChart({
      name: 'The sky right now', date: dt.toISODate()!, time: dt.toFormat('HH:mm'), place: 'London',
      latitude: 51.5074, longitude: -0.1278, timezone: 'Europe/London', houseSystem: 'placidus',
    })
  }, [])
  const sun = now.placements[0]
  const moon = now.placements[1]

  return (
    <div className="home">
      <section className="hero">
        <div className="hero-text">
          <p className="eyebrow">Your birth chart, clearly explained</p>
          <h1>Understand yourself through the sky you were born under.</h1>
          <p className="lede">
            Enter your birth details and get an accurate natal chart with plain-language insights on your personality,
            strengths and growth path. Every insight shows the rule behind it, so you can learn astrology as you go.
          </p>
          <div className="hero-cta">
            <Link to="/chart" className="btn primary">Create my free chart</Link>
            <Link to="/learn" className="btn ghost">Start learning</Link>
          </div>
          <ul className="trust-list">
            <li>Astronomy-grade positions (±1′)</li>
            <li>Calculated privately in your browser</li>
            <li>Transparent, rule-based readings</li>
          </ul>
        </div>
        <div className="hero-wheel">
          <ChartWheel chart={now} caption={`Live sky over London: the Sun is in ${sun.sign} and the Moon is in ${moon.sign}.`} />
        </div>
      </section>

      <section className="features">
        <div className="card feature">
          <span className="feature-icon" aria-hidden>☉</span>
          <h2>Accurate charts</h2>
          <p>Planet positions from the open-source Astronomy Engine, historical time zones for your birthplace, and a choice of Placidus, Whole Sign or Equal houses.</p>
        </div>
        <div className="card feature">
          <span className="feature-icon" aria-hidden>⚖</span>
          <h2>Readings you can trust</h2>
          <p>No vague horoscopes. Each insight is generated by a clear astrological rule, such as a planet’s sign, house, dignity or aspect, and tells you exactly why it applies.</p>
        </div>
        <div className="card feature">
          <span className="feature-icon" aria-hidden>✦</span>
          <h2>Learn step by step</h2>
          <p>Fifteen lessons from beginner to advanced, with worked examples, quizzes and prompts to explore your own chart.</p>
        </div>
      </section>

      <section className="sign-strip" aria-label="The twelve signs">
        {SIGNS.map((s) => (
          <div key={s.name} className={`sign-chip el-${s.element.toLowerCase()}`}>
            <span className="sign-chip-glyph" aria-hidden>{s.glyph}</span>
            <span>{s.name}</span>
            <span className="muted small">{s.dates}</span>
          </div>
        ))}
      </section>

      <section className="how card">
        <h2>How it works</h2>
        <ol className="steps">
          <li><strong>Enter your birth date, time and place.</strong> The exact time matters for your rising sign and houses.</li>
          <li><strong>We calculate the sky.</strong> Your local time is converted to UTC, planets are placed along the ecliptic, and houses are computed for your latitude.</li>
          <li><strong>Rules turn geometry into insight.</strong> Clear, published rules combine planet, sign, house, dignity and aspect meanings into a reading about you.</li>
          <li><strong>Save it (optional).</strong> Sign in with Google to keep your charts. Only you can see them.</li>
        </ol>
      </section>
    </div>
  )
}
