export default function PrivacyPage() {
  return (
    <article className="lesson">
      <header>
        <h1>Privacy &amp; security</h1>
      </header>
      <h2>Your chart is calculated on your device</h2>
      <p>All astronomical and astrological calculations run in your browser. Your birth date and time are never sent to our servers to generate a chart.</p>
      <h2>What leaves your browser</h2>
      <ul className="lesson-list">
        <li><strong>Place search:</strong> the text you type in the birthplace box is sent to the Open-Meteo geocoding service to find coordinates and a time zone. Nothing else is sent with it.</li>
        <li><strong>Saved charts (optional):</strong> if you sign in and press “Save chart”, the name, birth date, time and place are stored in our database. Row-level security ensures only your account can read, change or delete them.</li>
        <li><strong>Sign-in:</strong> Google sign-in is handled by Supabase Auth. We receive your name, email address and a user ID. We never see your Google password.</li>
        <li><strong>Hosting:</strong> the site is served by Cloudflare, which, like any web host, processes your IP address and browser type to deliver pages and block attacks. We do not add analytics or tracking on top of this.</li>
      </ul>
      <h2>What stays on your device</h2>
      <p>The site keeps a few things in your browser's local storage so they survive a reload: your display settings (chart style, ayanamsa and so on), which lessons you have finished, the birth star you picked on the Panchang page, and, if you sign in, the sign-in session. None of this is sent anywhere. Clearing your browser's site data removes it.</p>
      <h2>Chart links</h2>
      <p>The “Copy link” button puts birth details into the part of the address after <code>#</code>, which browsers never send to web servers. Anyone you share the link with can see those details, though, so share it only with people you trust.</p>
      <h2>Security measures</h2>
      <ul className="lesson-list">
        <li>A strict Content Security Policy that allows scripts only from this site.</li>
        <li>OAuth with PKCE, and no secrets in the website code. The public Supabase key cannot bypass database security rules.</li>
        <li>No advertising, no analytics, no third-party trackers and no cookies.</li>
        <li>Database rules (row-level security) checked on the server: a signed-in user can read, add or delete only their own charts, and visitors who are not signed in can read nothing.</li>
        <li>The site cannot be embedded in other sites' frames, which blocks click-jacking.</li>
        <li>All content is rendered as text, never as raw HTML.</li>
      </ul>
      <h2>How long we keep data, and deleting it</h2>
      <p>Saved charts and your account are kept until you delete them. From <strong>My charts</strong> you can delete one chart, all of them with <strong>Delete all my charts</strong>, or everything with <strong>Delete my account</strong>, which also removes your name and email from our database. Deletion is immediate and permanent. To stop Google sharing your profile with this site, you can also remove Astro Life from your Google account's third-party connections.</p>
      <h2>About the readings</h2>
      <p>Astrology is a symbolic and reflective tradition, not a predictive science. Readings are generated by transparent rules and are meant for self-reflection only.</p>
    </article>
  )
}
