export default function PrivacyPage() {
  return (
    <article className="lesson">
      <header>
        <h1>Privacy &amp; security</h1>
      </header>
      <h2>Your chart is calculated on your device</h2>
      <p>All astronomical and astrological calculations run in your browser. Your birth date and time are never sent to our servers to generate a chart.</p>
      <h2>What leaves your browser</h2>
      <ul className="lesson-list">
        <li><strong>Place search:</strong> the text you type in the birthplace box is sent to the Open-Meteo geocoding service to find coordinates and a time zone. Nothing else is sent with it.</li>
        <li><strong>Saved charts (optional):</strong> if you sign in and press “Save chart”, the name, birth date, time and place are stored in our database. Row-level security ensures only your account can read, change or delete them.</li>
        <li><strong>Sign-in:</strong> Google sign-in is handled by Supabase Auth. We receive your name, email address and a user ID. We never see your Google password.</li>
      </ul>
      <h2>Chart links</h2>
      <p>The “Copy link” button puts birth details into the part of the address after <code>#</code>, which browsers never send to web servers. Anyone you share the link with can see those details, though, so share it only with people you trust.</p>
      <h2>Security measures</h2>
      <ul className="lesson-list">
        <li>A strict Content Security Policy that allows scripts only from this site.</li>
        <li>OAuth with PKCE, and no secrets in the website code. The public Supabase key cannot bypass database security rules.</li>
        <li>No advertising, no third-party trackers and no cookies beyond the sign-in session.</li>
        <li>All content is rendered as text, never as raw HTML.</li>
      </ul>
      <h2>Deleting your data</h2>
      <p>You can delete any saved chart, or all of them at once with <strong>Delete all my data</strong>, from <strong>My charts</strong>. Deletion is immediate and permanent.</p>
      <h2>About the readings</h2>
      <p>Astrology is a symbolic and reflective tradition, not a predictive science. Readings are generated by transparent rules and are meant for self-reflection only.</p>
    </article>
  )
}
