import type { Lesson } from './types'

export const BEGINNER: Lesson[] = [
  {
    slug: 'what-is-a-birth-chart',
    level: 'Beginner',
    title: 'What is a birth chart?',
    summary: 'A snapshot of the sky at the moment you were born, and how to read its basic layout.',
    minutes: 6,
    blocks: [
      { type: 'p', text: 'A **birth chart** (or natal chart) is a map of where the Sun, Moon and planets were, as seen from your birthplace, at the exact minute you were born. Astrologers read this map as a symbolic portrait of personality, motivations and life themes.' },
      { type: 'h', text: 'The three ingredients' },
      { type: 'list', items: [
        '**Planets** (including the Sun and Moon): *what* part of you is being described. Mars is drive, Venus is love, Mercury is the mind.',
        '**Signs**: *how* that part of you behaves. Mars in Aries acts quickly; Mars in Taurus acts slowly and steadily.',
        '**Houses**: *where* in life that energy plays out, such as career, relationships or home.',
      ] },
      { type: 'p', text: 'A fourth ingredient, **aspects**, describes the angles between planets and how different parts of you cooperate or clash. You will learn these in the Intermediate level.' },
      { type: 'h', text: 'Reading the wheel' },
      { type: 'p', text: 'The chart is drawn as a circle. The outer ring holds the 12 zodiac signs, each spanning 30°. The inner wedges are the 12 houses. The horizontal line is the horizon: the left end is the **Ascendant** (the eastern horizon, where the Sun rises), and the right end is the Descendant. Planets above the line were above the horizon at your birth.' },
      { type: 'example', title: 'Example: a sunrise birth', text: [
        'Someone born at sunrise has the Sun exactly on the Ascendant, on the left edge of the wheel. Someone born at noon has the Sun near the top of the chart, the Midheaven.',
        'That is why the same birthday can produce very different charts. The Sun sign stays the same all day, but the rising sign and house positions change roughly every two hours.',
      ] },
      { type: 'callout', tone: 'tip', text: 'Birth time matters. Without it you still get accurate planet signs (except, occasionally, the Moon), but you lose the rising sign and houses.' },
      { type: 'try', text: 'Create your chart and find your Sun on the wheel. Is it above or below the horizon?' },
    ],
    quiz: [
      { q: 'In the formula "planet in sign in house", what does the sign describe?', options: ['What', 'How', 'Where', 'When'], answer: 1, explain: 'Planets are what, signs are how, houses are where.' },
      { q: 'Which point sits on the left (eastern) side of the wheel?', options: ['Midheaven', 'Descendant', 'Ascendant', 'IC'], answer: 2, explain: 'The Ascendant is the eastern horizon, drawn on the left.' },
    ],
  },
  {
    slug: 'signs',
    level: 'Beginner',
    title: 'The twelve signs',
    summary: 'Each sign is a style of behaviour, built from an element and a modality.',
    minutes: 9,
    blocks: [
      { type: 'p', text: 'The zodiac is the band of sky the Sun appears to travel through over a year. Western (tropical) astrology divides it into 12 equal 30° segments, starting from the spring equinox at 0° Aries.' },
      { type: 'p', text: 'Think of a sign as a **costume or style**, not a personality on its own. Any planet can wear any sign.' },
      { type: 'table', headers: ['Sign', 'Element', 'Modality', 'Ruler', 'In a phrase'], rows: [
        ['Aries ♈︎', 'Fire', 'Cardinal', 'Mars', 'I start'],
        ['Taurus ♉︎', 'Earth', 'Fixed', 'Venus', 'I build and keep'],
        ['Gemini ♊︎', 'Air', 'Mutable', 'Mercury', 'I connect ideas'],
        ['Cancer ♋︎', 'Water', 'Cardinal', 'Moon', 'I protect'],
        ['Leo ♌︎', 'Fire', 'Fixed', 'Sun', 'I express'],
        ['Virgo ♍︎', 'Earth', 'Mutable', 'Mercury', 'I refine'],
        ['Libra ♎︎', 'Air', 'Cardinal', 'Venus', 'I balance'],
        ['Scorpio ♏︎', 'Water', 'Fixed', 'Mars (Pluto)', 'I go deep'],
        ['Sagittarius ♐︎', 'Fire', 'Mutable', 'Jupiter', 'I seek'],
        ['Capricorn ♑︎', 'Earth', 'Cardinal', 'Saturn', 'I achieve'],
        ['Aquarius ♒︎', 'Air', 'Fixed', 'Saturn (Uranus)', 'I innovate'],
        ['Pisces ♓︎', 'Water', 'Mutable', 'Jupiter (Neptune)', 'I dissolve and imagine'],
      ] },
      { type: 'h', text: 'Opposite signs are partners' },
      { type: 'p', text: 'Signs directly across the wheel share a theme from opposite angles: Aries (self) and Libra (other); Taurus (my resources) and Scorpio (shared resources); Gemini (local facts) and Sagittarius (big truths); Cancer (home) and Capricorn (public role); Leo (personal creativity) and Aquarius (the collective); Virgo (practical service) and Pisces (compassion without limits).' },
      { type: 'example', title: 'Example: the same planet in two signs', text: [
        '**Mercury in Gemini** thinks fast, jumps between topics and loves banter. It might have three tabs open, a podcast on and a text half-written.',
        '**Mercury in Capricorn** thinks in plans and structures. It reads the manual, drafts an outline and speaks only when it has something useful to say.',
        'Both are "the mind"; the sign changes the style completely.',
      ] },
      { type: 'callout', tone: 'note', text: 'Sun-sign horoscopes only use one of your ten planets. Everyone has all twelve signs somewhere in their chart.' },
    ],
    quiz: [
      { q: 'What is the element and modality of Leo?', options: ['Fire, Cardinal', 'Fire, Fixed', 'Earth, Fixed', 'Air, Mutable'], answer: 1, explain: 'Leo is fixed fire: steady, warm, radiant.' },
      { q: 'Which sign is opposite Taurus?', options: ['Scorpio', 'Libra', 'Virgo', 'Capricorn'], answer: 0, explain: 'Taurus and Scorpio share the theme of resources and attachment.' },
    ],
  },
  {
    slug: 'elements-modalities',
    level: 'Beginner',
    title: 'Elements and modalities',
    summary: 'The building blocks behind the signs, and how to find your chart’s overall temperament.',
    minutes: 8,
    blocks: [
      { type: 'h', text: 'The four elements' },
      { type: 'table', headers: ['Element', 'Signs', 'Core drive', 'When strong', 'When missing'], rows: [
        ['Fire', 'Aries, Leo, Sagittarius', 'Inspiration and action', 'Enthusiastic, bold, inspiring', 'May lack spontaneous motivation'],
        ['Earth', 'Taurus, Virgo, Capricorn', 'Practicality and results', 'Grounded, reliable, productive', 'Ideas may not land in reality'],
        ['Air', 'Gemini, Libra, Aquarius', 'Ideas and connection', 'Communicative, objective, social', 'May struggle to step back and reflect'],
        ['Water', 'Cancer, Scorpio, Pisces', 'Feeling and intuition', 'Empathic, perceptive, deep', 'Emotions may feel foreign'],
      ] },
      { type: 'h', text: 'The three modalities' },
      { type: 'list', items: [
        '**Cardinal** (Aries, Cancer, Libra, Capricorn): starters. These signs begin each season and initiate action.',
        '**Fixed** (Taurus, Leo, Scorpio, Aquarius): sustainers. These signs fall mid-season and stabilise and persist.',
        '**Mutable** (Gemini, Virgo, Sagittarius, Pisces): adapters. These signs end each season and adjust and transition.',
      ] },
      { type: 'p', text: 'Each element appears once in each modality, so every sign is a unique pairing. Aries is **cardinal fire**, a spark that starts things; Leo is **fixed fire**, a steady hearth; Sagittarius is **mutable fire**, a wildfire that spreads.' },
      { type: 'h', text: 'Weighting a chart' },
      { type: 'p', text: 'To find your overall temperament, count placements by element, giving more weight to the most personal points. Astro Life uses this rule: Sun, Moon and Ascendant count 3; Mercury, Venus and Mars count 2; Jupiter, Saturn and the Midheaven count 1; Uranus, Neptune and Pluto count 0.5.' },
      { type: 'example', title: 'Worked example', text: [
        'Sun Aries (3 Fire), Moon Cancer (3 Water), Asc Virgo (3 Earth), Mercury Aries (2 Fire), Venus Taurus (2 Earth), Mars Gemini (2 Air), Jupiter Leo (1 Fire), Saturn Pisces (1 Water), MC Gemini (1 Air).',
        'Totals: Fire 6, Earth 5, Water 4, Air 3. This person is fire-led (energetic and initiating) with reasonable grounding, and air is the least developed function: they may act before reflecting.',
      ] },
      { type: 'try', text: 'Open your chart’s Overview tab to see your weighted element and modality bars.' },
    ],
    quiz: [
      { q: 'Which modality do Taurus, Leo, Scorpio and Aquarius share?', options: ['Cardinal', 'Fixed', 'Mutable'], answer: 1, explain: 'They fall in the middle of each season: fixed, persistent.' },
      { q: 'Sagittarius is…', options: ['Cardinal fire', 'Fixed fire', 'Mutable fire', 'Mutable air'], answer: 2, explain: 'The last fire sign of the cycle: adaptable, roaming fire.' },
    ],
  },
  {
    slug: 'planets',
    level: 'Beginner',
    title: 'The planets',
    summary: 'Ten bodies, ten parts of the psyche: personal, social and generational planets.',
    minutes: 10,
    blocks: [
      { type: 'p', text: 'In astrology the Sun and Moon are called planets too. Each one represents a distinct **function** or drive within you.' },
      { type: 'table', headers: ['Planet', 'Represents', 'Question it answers', 'Time to circle the zodiac'], rows: [
        ['☉ Sun', 'Identity, vitality, purpose', 'Who am I becoming?', '1 year'],
        ['☽ Moon', 'Emotions, needs, instincts', 'What makes me feel safe?', '~28 days'],
        ['☿ Mercury', 'Mind, communication', 'How do I think?', '~1 year'],
        ['♀ Venus', 'Love, values, beauty', 'What do I value?', '~1 year'],
        ['♂ Mars', 'Drive, desire, courage', 'How do I pursue?', '~2 years'],
        ['♃ Jupiter', 'Growth, luck, belief', 'Where do I expand?', '~12 years'],
        ['♄ Saturn', 'Structure, discipline, time', 'Where must I mature?', '~29 years'],
        ['♅ Uranus', 'Freedom, innovation', 'Where do I break rules?', '~84 years'],
        ['♆ Neptune', 'Dreams, ideals, spirituality', 'Where do I merge?', '~165 years'],
        ['♇ Pluto', 'Power, transformation', 'Where do I transform?', '~248 years'],
      ] },
      { type: 'h', text: 'Three tiers' },
      { type: 'list', items: [
        '**Personal planets** (Sun, Moon, Mercury, Venus, Mars) move quickly, so their signs vary between people born weeks apart. They describe your everyday personality.',
        '**Social planets** (Jupiter, Saturn) describe how you grow and mature within society.',
        '**Generational planets** (Uranus, Neptune, Pluto) stay in one sign for 7–30 years. Their *sign* describes your generation, while their *house* and *aspects* make them personal.',
      ] },
      { type: 'h', text: 'Retrograde planets' },
      { type: 'p', text: 'Sometimes a planet appears to move backward from Earth’s point of view. This is an optical effect, like a slower car seeming to drift backward as you overtake it. In a birth chart, a retrograde planet is usually read as an energy that is **internalised**, reflected on and revisited before being expressed outwardly.' },
      { type: 'example', title: 'Example: two people born a week apart', text: [
        'They may share a Sun sign and have the same Jupiter, Saturn and outer planets. But the Moon moves about 90° in a week, so their emotional natures will likely differ a lot. Their Mercury, Venus and Mars could differ too, depending on whether those planets were changing sign that week.',
      ] },
    ],
    quiz: [
      { q: 'Which planet moves fastest through the zodiac?', options: ['Mercury', 'Sun', 'Moon', 'Venus'], answer: 2, explain: 'The Moon moves roughly 13° per day.' },
      { q: 'Why is Pluto’s sign considered generational?', options: ['It is far away', 'It stays in one sign for many years', 'It is a dwarf planet', 'It is always retrograde'], answer: 1, explain: 'Everyone born within many years shares the same Pluto sign.' },
    ],
  },
  {
    slug: 'big-three',
    level: 'Beginner',
    title: 'Your Big Three: Sun, Moon, Rising',
    summary: 'The three most personal points, and how they layer into one personality.',
    minutes: 8,
    blocks: [
      { type: 'p', text: 'If you learn just three things about a chart, learn these:' },
      { type: 'list', items: [
        '**Sun sign**: your core identity and what you are growing into. It is what energises you.',
        '**Moon sign**: your emotional nature. It shows what you need to feel safe and how you react when no one is watching.',
        '**Rising sign (Ascendant)**: your approach, style and first impression. It is the "front door" of your personality.',
      ] },
      { type: 'p', text: 'An analogy: the Sun is **the driver**, the Moon is **the passenger who needs comfort**, and the Rising sign is **the car** that everyone else sees coming down the street.' },
      { type: 'example', title: 'Example: Capricorn Sun, Pisces Moon, Leo Rising', text: [
        '**Leo Rising**: people first meet someone warm, confident and a little dramatic, who is easy to notice in a room.',
        '**Capricorn Sun**: underneath is someone deeply ambitious, responsible and strategic, playing a long game.',
        '**Pisces Moon**: in private they are sensitive, dreamy and absorb other people’s moods. They need quiet and creativity to recharge.',
        'Synthesis: a confident public presence (Leo) serving serious goals (Capricorn), powered by an imaginative, compassionate inner world (Pisces) that few see. Friends might be surprised by how soft they are at home.',
      ] },
      { type: 'callout', tone: 'tip', text: 'When your Sun and Moon are in compatible elements (fire/air or earth/water), you tend to feel inwardly consistent. When they clash (such as fire and water), you have a richer but more complex inner dialogue.' },
      { type: 'try', text: 'Look at your Overview. Do your Sun, Moon and Rising share an element, or are they all different?' },
    ],
    quiz: [
      { q: 'Which of the Big Three requires an accurate birth time?', options: ['Sun', 'Moon', 'Rising', 'All three'], answer: 2, explain: 'The Ascendant changes sign about every 2 hours.' },
    ],
  },
]
