import type { Lesson } from './types'

export const INTERMEDIATE: Lesson[] = [
  {
    slug: 'houses',
    level: 'Intermediate',
    title: 'The twelve houses',
    summary: 'Where in life each planet’s energy plays out, from self to the unseen.',
    minutes: 11,
    blocks: [
      { type: 'p', text: 'Houses divide the sky around your birthplace into 12 areas of life. They depend on the **exact time and place** of birth, which is why two people born on the same day in different cities have different houses.' },
      { type: 'table', headers: ['House', 'Life area', 'Natural sign'], rows: [
        ['1st', 'Self, body, appearance, approach to life', 'Aries'],
        ['2nd', 'Money, possessions, self-worth, talents', 'Taurus'],
        ['3rd', 'Communication, siblings, learning, neighbourhood', 'Gemini'],
        ['4th', 'Home, family, roots, private life', 'Cancer'],
        ['5th', 'Creativity, romance, children, play', 'Leo'],
        ['6th', 'Daily work, health, routines, service', 'Virgo'],
        ['7th', 'Partnerships, marriage, open rivals', 'Libra'],
        ['8th', 'Intimacy, shared money, crisis, rebirth', 'Scorpio'],
        ['9th', 'Travel, higher learning, belief, publishing', 'Sagittarius'],
        ['10th', 'Career, reputation, public role', 'Capricorn'],
        ['11th', 'Friends, groups, networks, hopes', 'Aquarius'],
        ['12th', 'Solitude, the unconscious, spirituality', 'Pisces'],
      ] },
      { type: 'h', text: 'Angular, succedent, cadent' },
      { type: 'list', items: [
        '**Angular houses** (1, 4, 7, 10) sit on the four angles. Planets here are highly visible and powerful in your life.',
        '**Succedent houses** (2, 5, 8, 11) follow the angles. They stabilise and accumulate resources, pleasure and bonds.',
        '**Cadent houses** (3, 6, 9, 12) fall away from the angles. They are about learning, adjusting and preparing.',
      ] },
      { type: 'h', text: 'Empty houses are normal' },
      { type: 'p', text: 'With ten planets and twelve houses, at least two houses are always empty. An empty house is not missing from your life. Look at the **sign on its cusp** and where that sign’s ruler sits in your chart.' },
      { type: 'example', title: 'Deep example: Venus in the 10th vs the 4th', text: [
        '**Venus in the 10th house**: love, beauty and diplomacy show up in public life. This person might work in design, fashion, HR or diplomacy, or simply be well-liked at work. Their reputation may rest on charm.',
        '**Venus in the 4th house**: love and beauty are poured into the home. This person needs a beautiful, peaceful living space and may have warm family bonds or a devotion to their private sanctuary.',
        'Same planet, same sign, and the life emphasis still shifts completely with the house.',
      ] },
      { type: 'try', text: 'In your Placements tab, look for any house holding two or more planets. That area is a major focus in your life.' },
    ],
    quiz: [
      { q: 'Which houses are angular?', options: ['1, 4, 7, 10', '2, 5, 8, 11', '3, 6, 9, 12', '1, 5, 9'], answer: 0, explain: 'They begin at the four angles: Ascendant, IC, Descendant, Midheaven.' },
      { q: 'A planet in the 6th house most directly concerns…', options: ['Friends', 'Daily work and health', 'Travel', 'Marriage'], answer: 1, explain: 'The 6th house is routines, work and health.' },
    ],
  },
  {
    slug: 'angles',
    level: 'Intermediate',
    title: 'The four angles',
    summary: 'Ascendant, Descendant, Midheaven and IC: the chart’s compass points.',
    minutes: 7,
    blocks: [
      { type: 'p', text: 'The four angles are where the horizon and meridian cross the zodiac at your birth. They are the most time-sensitive points in the chart, moving about 1° every four minutes.' },
      { type: 'list', items: [
        '**Ascendant (AC)**, the eastern horizon: self, body, approach. It is the cusp of the 1st house.',
        '**Descendant (DC)**, the western horizon: partners and what you seek in others. It is the cusp of the 7th house.',
        '**Midheaven (MC)**, the highest point of the ecliptic: vocation, reputation, public aspirations.',
        '**Imum Coeli (IC)**, the lowest point: roots, home, ancestry, private self.',
      ] },
      { type: 'p', text: 'Planets within a few degrees of an angle are called **angular** and are among the most noticeable features of a person.' },
      { type: 'example', title: 'Example: Sun conjunct the Midheaven', text: [
        'Someone born near noon has the Sun near the MC. Their identity is tied to their public role: they often want a visible career and to be known for their work.',
        'By contrast, a birth near midnight puts the Sun near the IC. The identity is anchored in private life, family or inner work, and success may be measured in personal rather than public terms.',
      ] },
      { type: 'callout', tone: 'warn', text: 'If your birth time is uncertain by even 15 minutes, your Ascendant may shift by several degrees. Treat angle-based insights with care unless your time comes from a birth certificate.' },
    ],
    quiz: [
      { q: 'The Descendant is associated with…', options: ['Career', 'Partners', 'Home', 'Body'], answer: 1, explain: 'It is the 7th house cusp: others and partnership.' },
    ],
  },
  {
    slug: 'aspects',
    level: 'Intermediate',
    title: 'Aspects: how planets talk to each other',
    summary: 'The five major angles, orbs, and how to interpret a planetary conversation.',
    minutes: 12,
    blocks: [
      { type: 'p', text: 'An **aspect** is a meaningful angle between two planets along the zodiac. Aspects show which parts of you cooperate, merge or clash.' },
      { type: 'table', headers: ['Aspect', 'Angle', 'Default orb*', 'Nature', 'Feels like'], rows: [
        ['☌ Conjunction', '0°', '8°', 'Blending', 'Two energies fused as one'],
        ['⚹ Sextile', '60°', '4°', 'Opportunity', 'A helpful friend, if you call them'],
        ['□ Square', '90°', '7°', 'Tension', 'Friction that forces growth'],
        ['△ Trine', '120°', '7°', 'Flow', 'Natural, easy talent'],
        ['☍ Opposition', '180°', '8°', 'Polarity', 'A see-saw that needs balancing'],
      ] },
      { type: 'p', text: '*Astro Life adds 2° to the orb when the Sun or Moon is involved and subtracts 2° for the angles and the Node. Orb conventions vary between astrologers; there is no single "correct" orb.' },
      { type: 'h', text: 'Orb = strength' },
      { type: 'p', text: 'The closer an aspect is to exact, the stronger it is felt. A 0.5° square is a defining feature; a 6° square is a background hum.' },
      { type: 'h', text: 'Applying vs separating' },
      { type: 'p', text: 'If the faster planet is moving toward the exact angle, the aspect is **applying**, an energy that is building. If it has passed exact, it is **separating**, an energy that is more familiar and integrated.' },
      { type: 'h', text: 'How to interpret any aspect' },
      { type: 'list', items: [
        '1. Name what each planet represents (Moon = feelings, Saturn = responsibility).',
        '2. Apply the aspect’s nature (square = friction that motivates).',
        '3. Colour it with the signs and houses involved.',
        '4. Say it in one sentence, then add nuance.',
      ] },
      { type: 'example', title: 'Deep example: Moon square Saturn', text: [
        '**Step 1**: Moon = emotional needs, comfort. Saturn = limits, duty, authority.',
        '**Step 2**: Square = these two frustrate each other and demand work.',
        '**One sentence**: "Your need for comfort bumps against a strong sense of duty."',
        '**Nuance**: this person may have learned to hold back feelings early, perhaps with a serious parent or early responsibilities. In adulthood that becomes remarkable emotional resilience and reliability. The growth task is to give themselves the nurturing they give others.',
        'Compare **Moon trine Saturn**: the same planets in flow. Emotional steadiness comes naturally, as a calm, mature presence people lean on.',
      ] },
      { type: 'callout', tone: 'note', text: '"Hard" aspects are not bad. Many accomplished people have challenging squares; tension creates drive. Too many trines can make life comfortable but unmotivated.' },
      { type: 'try', text: 'Open your Aspects tab. Your tightest aspect (smallest orb) is listed first. Try interpreting it yourself before reading ours.' },
    ],
    quiz: [
      { q: 'Which aspect is 120°?', options: ['Square', 'Sextile', 'Trine', 'Opposition'], answer: 2, explain: 'Trine = one third of the circle.' },
      { q: 'Which is stronger?', options: ['A square with 0.8° orb', 'A square with 6° orb'], answer: 0, explain: 'Tighter orbs are more strongly felt.' },
    ],
  },
  {
    slug: 'rulership',
    level: 'Intermediate',
    title: 'Rulerships, dignities and the chart ruler',
    summary: 'How signs are linked to planets, and why some placements are “stronger”.',
    minutes: 10,
    blocks: [
      { type: 'p', text: 'Every sign has a **ruling planet**, the planet that is most at home there. This creates a web of connections across the chart.' },
      { type: 'table', headers: ['Planet', 'Domicile (home)', 'Exaltation', 'Detriment', 'Fall'], rows: [
        ['Sun', 'Leo', 'Aries', 'Aquarius', 'Libra'],
        ['Moon', 'Cancer', 'Taurus', 'Capricorn', 'Scorpio'],
        ['Mercury', 'Gemini, Virgo', 'Virgo', 'Sagittarius, Pisces', 'Pisces'],
        ['Venus', 'Taurus, Libra', 'Pisces', 'Scorpio, Aries', 'Virgo'],
        ['Mars', 'Aries, Scorpio', 'Capricorn', 'Libra, Taurus', 'Cancer'],
        ['Jupiter', 'Sagittarius, Pisces', 'Cancer', 'Gemini, Virgo', 'Capricorn'],
        ['Saturn', 'Capricorn, Aquarius', 'Libra', 'Cancer, Leo', 'Aries'],
      ] },
      { type: 'list', items: [
        '**Domicile**: the planet is at home and expresses itself naturally.',
        '**Exaltation**: an honoured guest, showing its best qualities.',
        '**Detriment**: the sign opposite home. The planet works in an unfamiliar way, which is challenging but can produce unusual skill.',
        '**Fall**: opposite exaltation. The planet may lack confidence at first and grows through conscious effort.',
      ] },
      { type: 'h', text: 'The chart ruler' },
      { type: 'p', text: 'The ruler of your rising sign is your **chart ruler**. Its sign, house and aspects become a master theme in your life. For Cancer rising the chart ruler is the Moon; for Libra rising it is Venus.' },
      { type: 'example', title: 'Deep example: following the ruler', text: [
        'Take someone with **Gemini rising**. Their chart ruler is Mercury. Suppose Mercury is in Capricorn in the 8th house.',
        'Reading: the Gemini first impression is chatty and curious, but the life journey is steered by a strategic, serious mind (Capricorn) directed toward depth, research, psychology or shared finances (8th house). This person might present as light and witty yet build a career in something like forensic accounting or psychotherapy.',
        'This "follow the ruler" chain is one of the most useful techniques in chart reading.',
      ] },
      { type: 'callout', tone: 'note', text: 'Astro Life uses traditional rulers for the chart ruler (Mars for Scorpio, Saturn for Aquarius, Jupiter for Pisces) because they are the most tested. Many modern astrologers also consider Pluto, Uranus and Neptune as co-rulers.' },
    ],
    quiz: [
      { q: 'Mars in Capricorn is…', options: ['Domicile', 'Exalted', 'Detriment', 'Fall'], answer: 1, explain: 'Mars is exalted in Capricorn: disciplined, strategic drive.' },
      { q: 'What is the chart ruler for Sagittarius rising?', options: ['Mars', 'Jupiter', 'Saturn', 'Sun'], answer: 1, explain: 'Jupiter rules Sagittarius.' },
    ],
  },
  {
    slug: 'reading-a-placement',
    level: 'Intermediate',
    title: 'Putting it together: reading a placement',
    summary: 'A repeatable formula, practised on a real historical chart.',
    minutes: 12,
    blocks: [
      { type: 'p', text: 'Every placement can be read with one formula:' },
      { type: 'callout', tone: 'tip', text: '**[Planet]** (what) expresses itself **[sign style]** (how), mainly in **[house area]** (where), shaped by **[aspects]** (with whom), and strengthened or strained by **[dignity]**.' },
      { type: 'p', text: 'This is exactly the rule chain Astro Life’s engine uses. Every insight on your chart shows the rule that produced it.' },
      { type: 'h', text: 'Case study: Albert Einstein' },
      { type: 'p', text: 'Born 14 March 1879, 11:30 local time, Ulm, Germany. Pisces Sun, Sagittarius Moon, Cancer Rising.' },
      { type: 'example', title: 'Mercury in Aries, 10th house, conjunct Saturn (orb 1°)', text: [
        '**What**: Mercury = the mind, thinking, communication.',
        '**How (Aries)**: direct, bold, pioneering. He is willing to think thoughts no one has thought before.',
        '**Where (10th house)**: career and public reputation. His ideas are what he is known for.',
        '**With whom (Saturn conjunction, 1°)**: structure, rigour, patience, time. Saturn gives the bold Aries mind discipline and staying power, and it literally governs *time*, the subject he reshaped.',
        '**Sentence**: "A revolutionary, disciplined mind becomes the foundation of a public legacy."',
      ] },
      { type: 'example', title: 'Mars in Capricorn, 7th house (exalted)', text: [
        '**What**: Mars = drive, will.',
        '**How (Capricorn, exalted)**: strategic, persistent, disciplined. This is Mars at its most effective.',
        '**Where (7th house)**: partnerships and collaborators, including rivals and debate partners.',
        '**Sentence**: "Determined energy that shows most clearly in one-to-one engagement." Think of his decades-long debates with Niels Bohr.',
      ] },
      { type: 'callout', tone: 'note', text: 'Case studies are illustrations of technique, not proof. Hindsight makes any chart look fitting, so the value is in learning the method.' },
      { type: 'try', text: 'Pick your Mercury placement and write your own one-sentence reading using the formula above, then compare it with ours.' },
    ],
    quiz: [
      { q: 'In the formula, what does the house tell you?', options: ['What', 'How', 'Where', 'With whom'], answer: 2, explain: 'Houses show the area of life.' },
    ],
  },
]
