import type { Lesson } from './types'

/**
 * Detailed Jyotish course. Real-life examples use birth data as commonly
 * published (Einstein and Jobs are birth-record quality; Gandhi and Vivekananda
 * are traditional data) and every placement quoted was computed by Astro Life.
 */
export const JYOTISH: Lesson[] = [
  {
    slug: 'vedic-rashis', level: 'Vedic', module: 'Foundations',
    title: 'The 12 rashis in Jyotish',
    summary: 'Movable, fixed and dual signs, odd and even signs, elements, lords, and the cosmic body of Kalapurusha.',
    minutes: 11,
    blocks: [
      { type: 'p', text: 'A **rashi** is a 30° sign of the sidereal zodiac. In Jyotish a sign is a **field** that gives a planet its style. Each rashi carries several classifications, and every one of them is used in real rules.' },
      { type: 'table', headers: ['Rashi', 'Lord', 'Nature', 'Element', 'Gender', 'Kalapurusha (body)'], rows: [
        ['Mesha (Aries)', 'Mars', 'Movable (chara)', 'Fire', 'Odd / male', 'Head'],
        ['Vrishabha (Taurus)', 'Venus', 'Fixed (sthira)', 'Earth', 'Even / female', 'Face, throat'],
        ['Mithuna (Gemini)', 'Mercury', 'Dual (dwiswabhava)', 'Air', 'Odd', 'Shoulders, arms'],
        ['Karka (Cancer)', 'Moon', 'Movable', 'Water', 'Even', 'Chest, heart'],
        ['Simha (Leo)', 'Sun', 'Fixed', 'Fire', 'Odd', 'Stomach, upper abdomen'],
        ['Kanya (Virgo)', 'Mercury', 'Dual', 'Earth', 'Even', 'Intestines, waist'],
        ['Tula (Libra)', 'Venus', 'Movable', 'Air', 'Odd', 'Lower abdomen, kidneys'],
        ['Vrishchika (Scorpio)', 'Mars', 'Fixed', 'Water', 'Even', 'Genitals'],
        ['Dhanu (Sagittarius)', 'Jupiter', 'Dual', 'Fire', 'Odd', 'Thighs'],
        ['Makara (Capricorn)', 'Saturn', 'Movable', 'Earth', 'Even', 'Knees'],
        ['Kumbha (Aquarius)', 'Saturn', 'Fixed', 'Air', 'Odd', 'Calves, ankles'],
        ['Meena (Pisces)', 'Jupiter', 'Dual', 'Water', 'Even', 'Feet'],
      ] },
      { type: 'h', text: 'Why each classification matters' },
      { type: 'list', items: [
        '**Movable / fixed / dual** determine the Navamsa starting point, travel and change (movable), stability (fixed) and adaptability (dual). A movable sign on the 10th often shows a career with travel or change.',
        '**Odd / even** decide the D2, D7 and D10 starting points and show assertive (odd) or receptive (even) expression.',
        '**Elements** give temperament: fire is pitta and drive, earth is practicality, air is ideas, water is feeling.',
        '**Kalapurusha** maps the zodiac onto a cosmic person. Aries is the head and Pisces the feet, which is why health is judged from the matching sign and house.',
      ] },
      { type: 'example', title: 'Real-life example: Mahatma Gandhi’s Tula (Libra) lagna', text: [
        'Gandhi’s lagna is **Tula**, a movable air sign ruled by Venus, the sign of the scales: balance, justice and negotiation.',
        'His lagna holds **Venus in its own sign**, with Mercury and Mars. Libra’s themes of fairness and diplomacy, energised by Mars, fit a life spent negotiating for justice through non-violent means.',
      ] },
    ],
    quiz: [
      { q: 'Which of these is a dual sign?', options: ['Aries', 'Leo', 'Virgo', 'Capricorn'], answer: 2, explain: 'Gemini, Virgo, Sagittarius and Pisces are dual.' },
      { q: 'In Kalapurusha, Aries represents…', options: ['Feet', 'Head', 'Heart', 'Knees'], answer: 1, explain: 'The zodiac starts at the head (Aries) and ends at the feet (Pisces).' },
    ],
  },
  {
    slug: 'vedic-bhavas', level: 'Vedic', module: 'Foundations',
    title: 'The 12 bhavas in depth',
    summary: 'Every house’s meanings, its natural significator (karaka), and the house groups every rule depends on.',
    minutes: 13,
    blocks: [
      { type: 'p', text: 'A **bhava** is a field of life. In whole-sign houses the lagna sign is the 1st bhava, the next sign the 2nd, and so on. Each bhava has a **karaka**, a planet that naturally signifies it.' },
      { type: 'table', headers: ['Bhava', 'Name', 'Signifies', 'Karaka'], rows: [
        ['1st', 'Tanu', 'Body, self, health, personality, overall life direction', 'Sun'],
        ['2nd', 'Dhana', 'Wealth, family, speech, food, face, early education', 'Jupiter'],
        ['3rd', 'Sahaja', 'Courage, younger siblings, effort, communication, short travel, hands', 'Mars'],
        ['4th', 'Sukha', 'Mother, home, land, vehicles, inner peace, schooling', 'Moon'],
        ['5th', 'Putra', 'Children, intelligence, creativity, romance, mantra, past merit', 'Jupiter'],
        ['6th', 'Ari', 'Enemies, disease, debt, litigation, service, competition', 'Mars & Saturn'],
        ['7th', 'Kalatra', 'Spouse, marriage, partnerships, business, public', 'Venus'],
        ['8th', 'Ayu', 'Longevity, sudden events, inheritance, research, occult, in-laws', 'Saturn'],
        ['9th', 'Dharma', 'Fortune, father, guru, higher learning, pilgrimage, ethics', 'Jupiter & Sun'],
        ['10th', 'Karma', 'Career, status, authority, action, reputation', 'Sun, Mercury, Jupiter, Saturn'],
        ['11th', 'Labha', 'Gains, income, elder siblings, friends, fulfilment of wishes', 'Jupiter'],
        ['12th', 'Vyaya', 'Losses, expenses, foreign lands, sleep, isolation, moksha', 'Saturn & Ketu'],
      ] },
      { type: 'h', text: 'The house groups' },
      { type: 'table', headers: ['Group', 'Houses', 'Character', 'Rule of thumb'], rows: [
        ['Kendra (angles)', '1, 4, 7, 10', 'Strength, action, visibility', 'Benefics here protect the whole chart'],
        ['Trikona (trines)', '1, 5, 9', 'Fortune, grace, dharma', 'The most auspicious houses; their lords are always good'],
        ['Dusthana', '6, 8, 12', 'Difficulty, loss, transformation', 'Their lords spoil the houses they join'],
        ['Upachaya', '3, 6, 10, 11', 'Growth over time', 'Malefics do well here'],
        ['Maraka', '2, 7', 'Houses that “kill” the 3rd and 8th (longevity)', 'Their lords are watched in health timing'],
        ['Moksha', '4, 8, 12', 'Liberation, the inner journey', 'Emphasis gives a spiritual bent'],
      ] },
      { type: 'h', text: 'Bhavat Bhavam: house from house' },
      { type: 'p', text: 'Any house can be treated as a new lagna. The 7th from the 7th (the 1st) shows how you appear to your partner; the 9th from the 9th (the 5th) shows your father’s fortune, your grandfather. This principle unlocks many classical rules.' },
      { type: 'example', title: 'Real-life example: Swami Vivekananda’s 10th house', text: [
        'His lagna is **Dhanu (Sagittarius)**, so Virgo is the 10th house of karma. The **Moon and Saturn** sit there together.',
        'The 10th shows one’s work in the world. The Moon (the public, the mind) with Saturn (renunciation, service to the masses, discipline) in the house of action describes a public life of austere service. He founded a monastic order devoted to serving the poor.',
      ] },
    ],
    quiz: [
      { q: 'The karaka of the 7th house is…', options: ['Jupiter', 'Venus', 'Mars', 'Saturn'], answer: 1, explain: 'Venus signifies the spouse and marriage.' },
      { q: 'Which houses are upachaya?', options: ['1, 5, 9', '3, 6, 10, 11', '6, 8, 12', '2, 7'], answer: 1, explain: 'Upachaya houses improve with time; malefics thrive there.' },
    ],
  },
  {
    slug: 'vedic-grahas', level: 'Vedic', module: 'The planets',
    title: 'The nine grahas in depth',
    summary: 'Nature, significations, relationships, and what each planet looks like when strong or weak.',
    minutes: 14,
    blocks: [
      { type: 'p', text: 'Graha means “that which seizes”. Each graha grabs a part of life and colours it. Learn each one on three levels: its **nature** (benefic or malefic), its **karakatva** (what it signifies) and its **relationships** with the other grahas.' },
      { type: 'table', headers: ['Graha', 'Strong gives', 'Weak or afflicted gives', 'Body', 'Gem · Day'], rows: [
        ['☉ Surya (Sun)', 'Confidence, leadership, vitality, government favour', 'Ego clashes, weak father-link, low stamina', 'Heart, bones, eyes', 'Ruby · Sunday'],
        ['☽ Chandra (Moon)', 'Emotional balance, popularity, nurturing', 'Anxiety, mood swings, restlessness', 'Mind, fluids, breasts', 'Pearl · Monday'],
        ['♂ Mangala (Mars)', 'Courage, drive, technical skill, property', 'Anger, accidents, conflict', 'Blood, muscles', 'Red coral · Tuesday'],
        ['☿ Budha (Mercury)', 'Intellect, speech, business sense, humour', 'Nervousness, indecision, skin issues', 'Nerves, skin, speech', 'Emerald · Wednesday'],
        ['♃ Guru (Jupiter)', 'Wisdom, children, fortune, ethics, wealth', 'Poor judgement, excess, liver issues', 'Liver, fat', 'Yellow sapphire · Thursday'],
        ['♀ Shukra (Venus)', 'Love, beauty, art, comforts, a happy marriage', 'Indulgence, relationship trouble', 'Reproductive system, kidneys', 'Diamond · Friday'],
        ['♄ Shani (Saturn)', 'Discipline, endurance, justice, longevity', 'Delays, depression, chronic illness', 'Joints, teeth, legs', 'Blue sapphire · Saturday'],
        ['☊ Rahu', 'Ambition, innovation, foreign success, fame', 'Obsession, deception, confusion', 'Poisons, phobias', 'Hessonite'],
        ['☋ Ketu', 'Spiritual insight, intuition, precision', 'Detachment, losses, sudden separation', 'Viral, mysterious ailments', 'Cat’s eye'],
      ] },
      { type: 'h', text: 'Natural relationships (naisargika maitri)' },
      { type: 'table', headers: ['Graha', 'Friends', 'Neutral', 'Enemies'], rows: [
        ['Sun', 'Moon, Mars, Jupiter', 'Mercury', 'Venus, Saturn'],
        ['Moon', 'Sun, Mercury', 'Mars, Jupiter, Venus, Saturn', '—'],
        ['Mars', 'Sun, Moon, Jupiter', 'Venus, Saturn', 'Mercury'],
        ['Mercury', 'Sun, Venus', 'Mars, Jupiter, Saturn', 'Moon'],
        ['Jupiter', 'Sun, Moon, Mars', 'Saturn', 'Mercury, Venus'],
        ['Venus', 'Mercury, Saturn', 'Mars, Jupiter', 'Sun, Moon'],
        ['Saturn', 'Mercury, Venus', 'Jupiter', 'Sun, Moon, Mars'],
      ] },
      { type: 'p', text: 'These relationships decide whether a planet is comfortable in another’s sign, and they drive **Graha Maitri** in kundali matching.' },
      { type: 'callout', tone: 'note', text: '**Benefic and malefic are natural tendencies, not moral labels.** Saturn in the right house gives more lasting success than Venus in the wrong one. Functional nature by lagna (a later lesson) can override natural nature.' },
      { type: 'example', title: 'Real-life example: Steve Jobs’s exalted Saturn', text: [
        'Jobs has **Leo lagna** with **Saturn exalted in Libra** in the 3rd house (effort, communication, craft).',
        'Saturn at full strength in the house of self-effort gives relentless perfectionism and discipline in making things. Libra, the sign of balance and beauty, gave that discipline an aesthetic direction.',
      ] },
    ],
    quiz: [
      { q: 'Which planet sees Mercury as an enemy?', options: ['Sun', 'Venus', 'Moon', 'Saturn'], answer: 2, explain: 'The Moon considers Mercury an enemy, though Mercury sees the Moon as a friend.' },
    ],
  },
  {
    slug: 'vedic-strength', level: 'Vedic', module: 'The planets',
    title: 'Judging planetary strength',
    summary: 'Exaltation, moolatrikona, own sign, combustion, retrogression, dig bala, vargottama and neecha bhanga.',
    minutes: 12,
    blocks: [
      { type: 'p', text: 'The same yoga can make one person famous and do little for another. The difference is **strength (bala)**. Before interpreting any planet, grade it with this checklist.' },
      { type: 'table', headers: ['Factor', 'Rule', 'Effect'], rows: [
        ['Exaltation (uchcha)', 'Sun Aries, Moon Taurus, Mars Capricorn, Mercury Virgo, Jupiter Cancer, Venus Pisces, Saturn Libra', 'Best results; the deep-exaltation degree is strongest'],
        ['Moolatrikona', 'e.g. Sun Leo 0–20°, Jupiter Sagittarius 0–10°', 'Like an office: authoritative and dependable'],
        ['Own sign (swakshetra)', 'Planet in a sign it rules', 'Comfortable and protective of its houses'],
        ['Friend / neutral / enemy sign', 'Relationship with the sign lord', 'Decreasing comfort'],
        ['Debilitation (neecha)', 'Opposite the exaltation sign', 'Weak, unless neecha bhanga applies'],
        ['Combustion (asta)', 'Within ~10–17° of the Sun (varies by planet)', 'Significations overshadowed'],
        ['Retrograde (vakri)', 'Apparent backward motion', 'Strong (cheshta bala) but unconventional'],
        ['Dig bala', 'Sun & Mars in the 10th, Jupiter & Mercury in the 1st, Moon & Venus in the 4th, Saturn in the 7th', 'Directional strength, very effective'],
        ['Vargottama', 'Same sign in D1 and D9', 'Reliable, consistent results'],
      ] },
      { type: 'h', text: 'Neecha Bhanga: when weakness becomes strength' },
      { type: 'p', text: 'A debilitated planet is “cancelled” (neecha bhanga) when, for example, the lord of its debilitation sign is in a kendra from the lagna or Moon, or it is aspected by its own dispositor. Such people often rise from difficult beginnings.' },
      { type: 'example', title: 'Real-life example: Einstein’s debilitated Mercury', text: [
        'Einstein’s **Mercury is debilitated in Pisces** and also combust. On paper that is weak logic and speech, and indeed he was a late talker and struggled with rote schooling.',
        'But Mercury’s dispositor **Jupiter sits in Aquarius, a kendra (the 4th) from his Moon**. That is **neecha bhanga**. Pisces Mercury thinks in images and intuition, not rules, and it became the source of his thought experiments. The rule chain is debilitation plus cancellation, giving extraordinary but unconventional intellect.',
      ] },
      { type: 'try', text: 'Open your **Grahas** tab: the dignity column and notes show exactly these factors for your chart.' },
    ],
    quiz: [
      { q: 'Which planets get dig bala in the 10th house?', options: ['Moon and Venus', 'Sun and Mars', 'Jupiter and Mercury', 'Saturn'], answer: 1, explain: 'The Sun and Mars are strongest at the top of the chart.' },
      { q: 'Vargottama means…', options: ['Retrograde in D9', 'Same sign in D1 and D9', 'Exalted in D10', 'Conjunct the Sun'], answer: 1, explain: 'Such a planet gives consistent, reliable results.' },
    ],
  },
  {
    slug: 'vedic-planets-in-houses', level: 'Vedic', module: 'The planets',
    title: 'Planets in the 12 houses: results and benefits',
    summary: 'A complete reference of what each graha gives in each bhava, plus the rules that modify it.',
    minutes: 16,
    blocks: [
      { type: 'p', text: 'This table is a starting point. Always modify it with **dignity**, **aspects** and **house lordship**. A strong Saturn in the 7th differs greatly from a debilitated one.' },
      { type: 'table', headers: ['House', 'Sun', 'Moon', 'Mars', 'Mercury', 'Jupiter'], rows: [
        ['1', 'Confident leader, strong vitality', 'Attractive, sensitive, popular', 'Energetic, bold; Mangal dosha', 'Witty, youthful, learned', 'Dig bala: wise, respected, protected'],
        ['2', 'Wealth via authority, commanding speech', 'Sweet speech, family wealth', 'Sharp speech, earns by effort', 'Eloquent, business income', 'Wealth, truthful speech, good family'],
        ['3', 'Courage, initiative', 'Creative communicator, travels', 'Very courageous, helps siblings', 'Writer, media, skilled hands', 'Wise siblings, measured effort'],
        ['4', 'Domestic tension, property via state', 'Dig bala: happy home, close to mother', 'Property, restless home; dosha', 'Good education, peaceful home', 'Happiness, vehicles, learning'],
        ['5', 'Intelligent, proud, leadership in creativity', 'Imaginative, emotionally intelligent', 'Sharp intellect, sports, speculation', 'Brilliant student, advisor', 'Good children, wisdom, mantra siddhi'],
        ['6', 'Defeats rivals, good health', 'Anxiety; talent for healing/service', 'Excellent: crushes enemies', 'Analytical, litigation skill', 'Overcomes obstacles; law or medicine'],
        ['7', 'Dominant partner, ego balance needed', 'Caring spouse, public dealings', 'Passionate marriage; dosha', 'Business partnerships, youthful spouse', 'Good spouse, wise partners'],
        ['8', 'Health watch, research, inheritance delays', 'Emotional depth, intuition', 'Accident caution, research; dosha', 'Research, occult study, long life', 'Long life, occult, inheritance'],
        ['9', 'Dharmic, influential father', 'Devotional, fortunate travels', 'Fights for beliefs', 'Scholarly, philosophical', 'Great fortune, guru’s grace'],
        ['10', 'Dig bala: fame, authority, government', 'Public career, changing roles', 'Dig bala: command, engineering', 'Commerce, communication career', 'Respected, ethical career'],
        ['11', 'Gains via authority, powerful friends', 'Gains through the public, many friends', 'Excellent gains through action', 'Gains from trade and intellect', 'Abundant gains'],
        ['12', 'Foreign lands, expenses, spiritual', 'Imagination, foreign residence, sleep issues', 'Expenses, foreign, bed pleasures; dosha', 'Foreign trade, spiritual study', 'Spiritual, charitable, foreign'],
      ] },
      { type: 'table', headers: ['House', 'Venus', 'Saturn', 'Rahu', 'Ketu'], rows: [
        ['1', 'Charming, artistic, comfortable', 'Serious, slow start, great perseverance', 'Ambitious, unconventional persona', 'Intuitive, detached, spiritual'],
        ['2', 'Wealth, sweet voice', 'Frugal, wealth after effort', 'Unusual speech or diet, sudden wealth', 'Detached from family wealth'],
        ['3', 'Artistic communication', 'Perseverance, courage that matures', 'Bold, media success (excellent)', 'Spiritual courage'],
        ['4', 'Dig bala: vehicles, beautiful home', 'Domestic burdens, old property', 'Restless home, foreign residence', 'Detachment from home'],
        ['5', 'Romance, creativity, children', 'Delayed children, serious mind', 'Unconventional intellect, speculation', 'Intuitive intelligence, mantra'],
        ['6', 'Relationship strain; arts or health service', 'Excellent: defeats enemies, service', 'Defeats enemies (excellent)', 'Healing ability, defeats rivals'],
        ['7', 'Attractive spouse, strong desire', 'Dig bala: mature, delayed but loyal marriage', 'Foreign or unconventional spouse', 'Detached partner, spiritual bond'],
        ['8', 'Wealth through spouse, secrecy', 'Long life, chronic issues', 'Sudden events, occult interest', 'Occult mastery'],
        ['9', 'Fortunate, refined beliefs', 'Unorthodox beliefs, strict father', 'Unorthodox beliefs, foreign gurus', 'Spiritual beliefs'],
        ['10', 'Career in arts, luxury, beauty', 'Hard-won high position', 'Ambition, sudden rise', 'Technical career, changes'],
        ['11', 'Gains, luxuries, female friends', 'Steady, large gains', 'Huge gains (excellent)', 'Gains, then detachment'],
        ['12', 'Bed pleasures, foreign comforts (good for Venus)', 'Isolation, foreign, discipline', 'Foreign lands, sleep issues', 'Moksha, liberation'],
      ] },
      { type: 'h', text: 'Rules that modify the table' },
      { type: 'list', items: [
        '**Benefics in kendras and trikonas** amplify good results; **malefics in upachayas** (3, 6, 10, 11) give success through struggle.',
        '**The planet’s own lordship matters.** Jupiter as a dusthana lord in the 1st gives mixed results for Taurus lagna (where Jupiter rules the 8th and 11th).',
        '**Aspects modify.** Jupiter’s aspect heals many afflictions; Saturn’s aspect delays and matures.',
        '**Dignity scales everything.** Exalted means the best version of the row; debilitated means the hardest version.',
      ] },
      { type: 'example', title: 'Real-life example: Jobs’s Venus in the 5th', text: [
        'Venus (beauty, design) in the **5th house** (creativity) of Leo lagna, conjunct **Rahu** (innovation, technology).',
        'Table: “romance, creativity”; Rahu adds “unconventional, technology”. Astro Life’s career engine ranks Venus as his top career significator, pointing to design and aesthetics: the calligraphy-inspired typography and product design he became known for.',
      ] },
    ],
    quiz: [
      { q: 'Malefics generally give good results in…', options: ['Kendras', 'Trikonas', 'Upachayas', 'The 8th'], answer: 2, explain: 'Upachaya houses (3, 6, 10, 11) reward the malefics’ struggle.' },
    ],
  },
  {
    slug: 'vedic-drishti', level: 'Vedic', module: 'Planetary relationships',
    title: 'Drishti: how planets look at each other',
    summary: 'The 7th-house aspect of every planet, the special aspects of Mars, Jupiter and Saturn, and how to use them.',
    minutes: 12,
    blocks: [
      { type: 'p', text: 'In Jyotish, aspects are counted by **whole signs**, not exact degrees. Every graha casts its **drishti** (glance) on the **7th sign** from itself. Three planets have extra, special aspects.' },
      { type: 'table', headers: ['Graha', 'Aspects (counting its own sign as 1)', 'Meaning of the special aspect'], rows: [
        ['Sun, Moon, Mercury, Venus', '7th only', '—'],
        ['Mars', '4th, 7th, 8th', 'Protects/attacks home (4th) and hidden matters (8th)'],
        ['Jupiter', '5th, 7th, 9th', 'Blesses intelligence (5th) and fortune (9th)'],
        ['Saturn', '3rd, 7th, 10th', 'Disciplines effort (3rd) and career (10th)'],
        ['Rahu, Ketu', '5th, 7th, 9th (modern practice)', 'Amplifies obsessively, like Jupiter’s reach without its wisdom'],
      ] },
      { type: 'h', text: 'How to use drishti' },
      { type: 'list', items: [
        '**Aspect on a house** colours all its matters. Jupiter aspecting the 7th protects marriage; Saturn aspecting it delays and matures marriage.',
        '**Aspect on a planet** modifies that planet. Jupiter aspecting a debilitated planet helps; Saturn aspecting the Moon brings seriousness to the mind.',
        '**Mutual aspect** (each aspects the other) creates a strong link, which counts like a conjunction for yogas.',
        '**Benefic aspects add, malefic aspects test.** Count both on the 1st, 7th and 10th for quick chart grading.',
      ] },
      { type: 'example', title: 'Worked example: Einstein’s Jupiter and Saturn', text: [
        '**Jupiter** is in Aquarius (9th house from Gemini lagna). Counting 5, 7 and 9 from Aquarius gives Gemini (1st), Leo (3rd) and Libra (5th). Jupiter blesses his **self** (1st), **courage and communication** (3rd) and **intelligence** (5th).',
        '**Saturn** is in Pisces (10th). Counting 3, 7 and 10 from Pisces gives Taurus (12th), Virgo (4th) and Sagittarius (7th). Saturn disciplines his solitude and research (12th), home (4th) and marriage (7th). His marriages were marked by duty, distance and strain, a classic Saturn-on-the-7th story.',
      ] },
      { type: 'callout', tone: 'tip', text: 'Jaimini astrology also uses **rashi drishti** (sign aspects: movable signs aspect fixed signs except the adjacent one, and dual signs aspect each other). Astro Life’s rules use Parashari graha drishti.' },
    ],
    quiz: [
      { q: 'Saturn in Aries aspects which signs?', options: ['Libra only', 'Gemini, Libra, Capricorn', 'Leo, Libra, Sagittarius', 'Cancer, Libra, Scorpio'], answer: 1, explain: '3rd from Aries is Gemini, 7th Libra, 10th Capricorn.' },
      { q: 'Jupiter aspects the…', options: ['4th, 7th, 8th', '5th, 7th, 9th', '3rd, 7th, 10th', '7th only'], answer: 1, explain: 'Jupiter’s special aspects are the 5th and 9th.' },
    ],
  },
  {
    slug: 'vedic-conjunctions', level: 'Vedic', module: 'Planetary relationships',
    title: 'Conjunctions: famous planetary combinations',
    summary: 'What happens when two grahas share a sign, from Budhaditya to Guru Chandal and the eclipse combinations.',
    minutes: 12,
    blocks: [
      { type: 'p', text: 'Planets in the same sign are **conjunct (yuti)**. They blend their significations. The closer their degrees, the stronger the blend, and the planet with the higher degree or greater strength usually dominates.' },
      { type: 'table', headers: ['Combination', 'Name', 'Typical result'], rows: [
        ['Sun + Mercury', 'Budhaditya', 'Intelligence, analytical skill, recognition for intellect'],
        ['Moon + Jupiter (or Jupiter in a kendra from the Moon)', 'Gajakesari', 'Wisdom, reputation, protection'],
        ['Moon + Mars', 'Chandra–Mangala', 'Enterprise, earning power, emotional intensity'],
        ['Mercury + Venus', '(Lakshmi–Narayana style)', 'Artistic intelligence, charm, commerce in beauty'],
        ['Jupiter + Venus', 'Two gurus', 'Refinement, wealth, but conflicting values (dharma vs pleasure)'],
        ['Mars + Saturn', '—', 'Enormous discipline or frustration; engineering, surgery, struggle'],
        ['Mars + Rahu', 'Angaraka', 'Explosive energy, accidents or a technological edge'],
        ['Jupiter + Rahu', 'Guru Chandala', 'Unorthodox beliefs, guru issues, sometimes a breakthrough innovator'],
        ['Sun + Rahu / Ketu', 'Grahana (eclipse)', 'Challenges with father or ego, strong ambition'],
        ['Moon + Rahu / Ketu', 'Grahana (eclipse)', 'Mental intensity, intuition, anxiety'],
        ['Moon + Saturn', 'Vish / Punarphoo', 'Emotional seriousness, depth, delay; maturity and endurance'],
        ['Venus + Saturn', '—', 'Loyal, lasting love that is late or serious; artistry with discipline'],
      ] },
      { type: 'h', text: 'Reading a conjunction step by step' },
      { type: 'list', items: [
        '1. Which planet is stronger (dignity, degree, lordship)? It leads.',
        '2. Are they friends or enemies? Friends cooperate; enemies create inner conflict.',
        '3. Which houses do they rule? The conjunction links those life areas.',
        '4. Which house do they occupy? That is where the blend manifests.',
      ] },
      { type: 'example', title: 'Real-life example: Vivekananda’s Moon–Saturn in the 10th', text: [
        'Moon (mind) + Saturn (renunciation, the masses, austerity) in Virgo (service) in the 10th house (work).',
        'Enemies by nature, they create a mind that finds no comfort in ordinary pleasures. Directed through the 10th, that becomes a renunciate’s public mission. He also has Mercury and Saturn in **parivartana** (exchange), binding intellect and service.',
      ] },
    ],
    quiz: [
      { q: 'Jupiter conjunct Rahu is called…', options: ['Gajakesari', 'Guru Chandala', 'Budhaditya', 'Angaraka'], answer: 1, explain: 'Guru Chandala: unorthodox beliefs or teachers.' },
    ],
  },
  {
    slug: 'vedic-functional', level: 'Vedic', module: 'Planetary relationships',
    title: 'Functional benefics and malefics by lagna',
    summary: 'Why Saturn can be your best friend and Jupiter your challenge: lordship changes a planet’s nature.',
    minutes: 10,
    blocks: [
      { type: 'p', text: 'Parashara teaches that a planet’s role depends on the **houses it rules** from your lagna. Lords of trikonas are always auspicious; lords of 6, 8 and 12 are troublesome; lords of kendras lose their natural nature (benefics become neutral, malefics become neutral too). A planet ruling both a kendra and a trikona is a **yogakaraka**.' },
      { type: 'table', headers: ['Lagna', 'Functional benefics', 'Functional malefics', 'Yogakaraka'], rows: [
        ['Aries', 'Sun, Jupiter, Mars', 'Mercury, Saturn, Venus (maraka)', '—'],
        ['Taurus', 'Saturn, Mercury, Sun', 'Jupiter, Moon, Venus (mixed)', 'Saturn'],
        ['Gemini', 'Venus, Mercury', 'Mars, Jupiter (kendra), Sun', '—'],
        ['Cancer', 'Mars, Jupiter, Moon', 'Venus, Mercury, Saturn', 'Mars'],
        ['Leo', 'Mars, Sun, Jupiter', 'Mercury, Venus, Saturn', 'Mars'],
        ['Virgo', 'Venus, Mercury', 'Mars, Moon, Jupiter (kendra)', '—'],
        ['Libra', 'Saturn, Mercury, Venus', 'Jupiter, Sun, Mars', 'Saturn'],
        ['Scorpio', 'Moon, Jupiter, Sun', 'Mercury, Venus', '—'],
        ['Sagittarius', 'Mars, Sun, Jupiter', 'Venus, Mercury (kendra), Saturn', '—'],
        ['Capricorn', 'Venus, Mercury, Saturn', 'Mars, Jupiter, Moon', 'Venus'],
        ['Aquarius', 'Venus, Saturn, Sun (7th lord)', 'Jupiter, Moon, Mars', 'Venus'],
        ['Pisces', 'Moon, Mars, Jupiter', 'Saturn, Venus, Sun, Mercury', '—'],
      ] },
      { type: 'callout', tone: 'note', text: 'Different schools weigh kendra lordship and maraka rules slightly differently, so small variations of this table exist.' },
      { type: 'example', title: 'Real-life example: Gandhi’s yogakaraka Saturn', text: [
        'For **Libra lagna**, Saturn rules the 4th (kendra) and 5th (trikona), which makes it the **yogakaraka**.',
        'In Gandhi’s chart Saturn sits in the 2nd house (speech, values) in Scorpio. His most powerful tool was disciplined, truthful speech and a severely simple lifestyle, a Saturnine yogakaraka expressed through the 2nd house.',
      ] },
    ],
    quiz: [
      { q: 'For Cancer and Leo lagnas the yogakaraka is…', options: ['Saturn', 'Venus', 'Mars', 'Jupiter'], answer: 2, explain: 'Mars rules a kendra and a trikona for both.' },
    ],
  },
  {
    slug: 'vedic-transits', level: 'Vedic', module: 'Divisional charts & timing',
    title: 'Transits (gochara): the moving sky',
    summary: 'Reading current planetary movement against your Moon and lagna: good houses, Sade Sati and the double transit.',
    minutes: 13,
    blocks: [
      { type: 'p', text: 'A **transit** is where a planet is today, read against your birth chart. In Jyotish transits are judged mainly **from the natal Moon** (the mind that experiences events) and also from the lagna. Transits **trigger** what the dasha allows: dasha is the season, transit is the weather.' },
      { type: 'table', headers: ['Transiting planet', 'Favourable houses from the Moon', 'Duration in a sign'], rows: [
        ['Sun', '3, 6, 10, 11', '~1 month'],
        ['Moon', '1, 3, 6, 7, 10, 11', '~2½ days'],
        ['Mars', '3, 6, 11', '~1½ months'],
        ['Mercury', '2, 4, 6, 8, 10, 11', '~1 month'],
        ['Jupiter', '2, 5, 7, 9, 11', '~1 year'],
        ['Venus', '1, 2, 3, 4, 5, 8, 9, 11, 12', '~1 month'],
        ['Saturn', '3, 6, 11', '~2½ years'],
        ['Rahu & Ketu', '3, 6, 11', '~1½ years'],
      ] },
      { type: 'h', text: 'Saturn’s famous transits' },
      { type: 'list', items: [
        '**Sade Sati**: Saturn in the 12th, 1st and 2nd from the Moon (~7½ years). Pressure, restructuring, maturity.',
        '**Ashtama Shani**: Saturn in the 8th from the Moon. Obstacles, health watchfulness and transformation.',
        '**Kantaka Shani**: Saturn in the 4th, 7th or 10th from the Moon. Friction in home, partnership or career.',
      ] },
      { type: 'h', text: 'The double-transit rule' },
      { type: 'p', text: 'A major event in a life area tends to occur when **transiting Jupiter and transiting Saturn both** occupy or aspect the relevant house or its lord, **and** the running dasha is connected to it. For marriage, watch the 7th house; for career, the 10th. Astro Life’s career and marriage reports compute these windows for you.' },
      { type: 'example', title: 'Worked example: timing a marriage', text: [
        'Suppose a Leo lagna person (7th house Aquarius, 7th lord Saturn) runs the **Venus–Saturn** dasha.',
        'Transiting Jupiter in Libra aspects Aquarius (its 5th aspect). Transiting Saturn in its own Aquarius occupies the 7th. Both touch the 7th, and the dasha is Venus (karaka) and Saturn (7th lord). All three conditions are met, which is the classical signature of the marriage year.',
      ] },
      { type: 'callout', tone: 'warn', text: 'Transits cannot give what the birth chart and dasha do not promise. Always read natal chart, then dasha, then transit.' },
    ],
    quiz: [
      { q: 'Sade Sati is Saturn transiting which houses from the Moon?', options: ['1, 4, 7', '12, 1, 2', '6, 8, 12', '3, 6, 11'], answer: 1, explain: 'Saturn’s passage over the Moon and its neighbours.' },
      { q: 'Jupiter transiting the 5th from the Moon is…', options: ['Favourable', 'Unfavourable'], answer: 0, explain: 'Jupiter is good in 2, 5, 7, 9, 11 from the Moon.' },
    ],
  },
  {
    slug: 'vedic-career', level: 'Vedic', module: 'Applied Jyotish',
    title: 'Career astrology: finding your profession',
    summary: 'The complete rule-based method: 10th house, livelihood significators, Amatyakaraka, D10, yogas and timing.',
    minutes: 16,
    blocks: [
      { type: 'p', text: 'Career analysis in Jyotish combines several independent techniques. When they agree, the conclusion is reliable. This is the exact method used by Astro Life’s career report.' },
      { type: 'list', items: [
        '1. **The 10th house from lagna, Moon and Sun**: lord, dignity, occupants and aspects (Phaladeepika considers all three).',
        '2. **Where the 10th lord goes**: e.g. in the 7th means business; in the 6th, service; in the 12th, foreign lands; in the 9th, teaching or law.',
        '3. **The navamsa dispositor of the 10th lord** (Phaladeepika 5.1): the lord of the navamsa sign occupied by the 10th lord reveals the *source of earnings*.',
        '4. **Amatyakaraka** (Jaimini): the planet with the second-highest degree is the career “minister”.',
        '5. **D10 Dasamsa**: lagna lord, 10th lord, occupants and strong planets.',
        '6. **Career yogas**: Dharma–Karmadhipati (9th + 10th lords), Raja yogas, Amala, Pancha Mahapurusha.',
        '7. **Mode of work**: 7th-house links suggest business; 6th-house links, employment; a strong Sun, government; 12th house or Rahu, foreign work.',
        '8. **Timing**: dashas of career significators plus double transit on the 10th.',
      ] },
      { type: 'h', text: 'Planet → profession' },
      { type: 'table', headers: ['Planet', 'Typical fields'], rows: [
        ['Sun', 'Government, administration, politics, medicine, executive leadership'],
        ['Moon', 'Nursing, hospitality, food, psychology, public relations, shipping'],
        ['Mars', 'Engineering, army, police, surgery, sports, real estate, manufacturing'],
        ['Mercury', 'Commerce, accounting, IT, writing, media, teaching, consulting'],
        ['Jupiter', 'Teaching, academia, law, finance, advisory, religious work'],
        ['Venus', 'Arts, film, music, fashion, design, luxury, hospitality, vehicles'],
        ['Saturn', 'Heavy industry, mining, oil, infrastructure, labour, logistics, judiciary'],
        ['Rahu', 'Technology, AI, foreign firms, aviation, mass media, pharmaceuticals'],
        ['Ketu', 'Research, programming, mathematics, astrology, alternative healing'],
      ] },
      { type: 'example', title: 'Real-life example: Einstein, from patent clerk to professor', text: [
        '10th lord **Jupiter** (Pisces 10th for Gemini lagna) sits in the **9th house** of higher learning. Rule: “10th lord in the 9th: teaching, law, philosophy, publishing”.',
        '9th lord Saturn sits in the 10th, making a **Jupiter–Saturn exchange**, the Dharma–Karmadhipati Raja Yoga. Four planets in the 10th, with exalted Venus forming Malavya yoga, give a highly visible life’s work.',
        'Astro Life’s engine, weighing all the rules, ranks **Jupiter** first (academia, research guidance, publishing knowledge). His early job as a patent clerk (service, examining inventions) fits Mercury and Saturn in the 10th, and academia followed.',
      ] },
      { type: 'example', title: 'Real-life example: Steve Jobs, a design-led technologist', text: [
        'Engine ranking: **Venus** first (design, aesthetics), then Jupiter and Saturn. Venus with **Rahu** (technology, innovation) in the 5th (creativity) describes a product visionary who fused beauty with technology.',
        'Exalted Saturn (the Amatyakaraka) in the 3rd gives the relentless perfectionism of craft.',
      ] },
      { type: 'try', text: 'Open **Explore your career** from your kundali to see every rule applied to your own chart.' },
    ],
    quiz: [
      { q: 'The navamsa dispositor rule uses which planet as its starting point?', options: ['Lagna lord', '10th lord', 'Moon', 'Saturn'], answer: 1, explain: 'Find the navamsa of the 10th lord, then take that sign’s lord.' },
      { q: 'Which planet is the Jaimini career significator?', options: ['Atmakaraka', 'Amatyakaraka', 'Darakaraka', 'Putrakaraka'], answer: 1, explain: 'The Amatyakaraka (2nd-highest degree) is the minister of career.' },
    ],
  },
  {
    slug: 'vedic-marriage', level: 'Vedic', module: 'Applied Jyotish',
    title: 'Marriage astrology: reading one chart',
    summary: 'The 7th house, Venus and Jupiter, D9, Darakaraka, Upapada, Mangal dosha, and timing marriage.',
    minutes: 16,
    blocks: [
      { type: 'p', text: 'From one person’s chart we can judge the **promise, nature, timing and stability** of marriage. We cannot judge a specific partner; that needs kundali matching.' },
      { type: 'list', items: [
        '1. **7th house** from lagna, Moon and Venus: lord, occupants, aspects. Jupiter’s aspect protects; Saturn’s delays.',
        '2. **Karakas**: Venus for everyone; Jupiter additionally for a woman’s husband. Check dignity, combustion and malefic contact.',
        '3. **Darakaraka** (lowest-degree planet): the nature of the spouse.',
        '4. **D9 Navamsa**: 7th house and lord, D9 lagna lord, and Venus and Jupiter in D9. Is the D1 7th lord strong in D9?',
        '5. **Upapada** (arudha of the 12th): the tangible marriage. Malefics in the 2nd from it test continuity; benefics sustain it.',
        '6. **Supporting houses**: 2nd (family), 4th (domestic happiness), 8th (longevity of the bond), and D7 for children.',
        '7. **Mangal dosha**: Mars in 1, 2, 4, 7, 8 or 12 from lagna, Moon or Venus, with cancellations.',
        '8. **Timing**: dashas of the 7th lord, Venus, Jupiter, the Darakaraka and planets in the 7th, plus double transit on the 7th.',
      ] },
      { type: 'h', text: 'Early or delayed?' },
      { type: 'table', headers: ['Tends toward early or timely', 'Tends toward delay'], rows: [
        ['Venus strong in a kendra or trikona', 'Saturn in or aspecting the 7th'],
        ['7th lord in the 1st, 2nd, 7th or 11th', '7th lord in the 6th, 8th or 12th'],
        ['Jupiter aspecting the 7th or its lord', 'Venus combust or debilitated'],
        ['Lagna lord linked with the 7th lord', 'Saturn linked with Venus or the 7th lord'],
        ['Venus–Mars link', 'Rahu or Ketu in the 7th; Moon–Saturn conjunction'],
      ] },
      { type: 'example', title: 'Real-life example: Vivekananda, the monk', text: [
        'For Sagittarius lagna the 7th is Gemini, ruled by **Mercury, which is combust** in the 2nd. **Saturn** in Virgo aspects Gemini (its 10th aspect), placing Saturn on the 7th house.',
        'The Darakaraka is Jupiter (in an enemy sign), and Venus is combust. Every delay indicator lines up, and Astro Life’s engine reads “marriage tends to come later, after maturity”. He took monastic vows and never married. The same indicators can also describe a spiritual path chosen over householder life.',
      ] },
      { type: 'example', title: 'Real-life example: Gandhi, married at 13', text: [
        'Libra lagna with **Venus in its own sign in the 1st**, and the 7th lord Mars also in the 1st: lagna lord and 7th lord conjunct. **Jupiter** sits in the 7th house itself.',
        'Every early indicator is present, and the engine reads “timely or early marriage indicated”. He was married to Kasturba at thirteen, in line with the custom of the time.',
      ] },
      { type: 'try', text: 'Open **Explore marriage** from your kundali to see your own timing tendency and favourable windows.' },
    ],
    quiz: [
      { q: 'Upapada Lagna is the arudha of which house?', options: ['7th', '12th', '2nd', '1st'], answer: 1, explain: 'UL = arudha of the 12th, which shows the tangible marriage.' },
      { q: 'Which aspect on the 7th is most protective?', options: ['Saturn', 'Mars', 'Jupiter', 'Rahu'], answer: 2, explain: 'Jupiter’s drishti blesses and sustains marriage.' },
    ],
  },
  {
    slug: 'vedic-matching', level: 'Vedic', module: 'Applied Jyotish',
    title: 'Kundali matching: Guna Milan and beyond',
    summary: 'All eight kootas explained, the ten South Indian poruthams, Mangal dosha matching and chart-level checks.',
    minutes: 16,
    blocks: [
      { type: 'p', text: 'Kundali matching compares two charts, mainly through the **Moon** (the mind), because marriage is lived day to day through emotions. The North Indian system is **Ashtakoota** (8 factors, 36 points); the South Indian system is **Dashakoota** (10 poruthams, pass/fail).' },
      { type: 'table', headers: ['Koota', 'Points', 'Based on', 'Measures'], rows: [
        ['Varna', '1', 'Moon sign (Brahmin/Kshatriya/Vaishya/Shudra classes of sign)', 'Spiritual and ego compatibility'],
        ['Vashya', '2', 'Moon sign group (human, quadruped, water, wild, insect)', 'Mutual attraction and influence'],
        ['Tara', '3', 'Nakshatra count mod 9 both ways', 'Destiny and wellbeing'],
        ['Yoni', '4', 'Nakshatra animal (14 animals)', 'Physical and intimate compatibility'],
        ['Graha Maitri', '5', 'Friendship of the Moon-sign lords', 'Mental compatibility'],
        ['Gana', '6', 'Deva / Manushya / Rakshasa nature of nakshatra', 'Temperament'],
        ['Bhakoot', '7', 'Moon-sign distance (2/12, 5/9, 6/8 are doshas)', 'Emotional bond and prosperity'],
        ['Nadi', '8', 'Adi / Madhya / Antya nadi of nakshatra', 'Health and progeny'],
      ] },
      { type: 'p', text: 'Guidance: **18+** acceptable, **25+** very good, **33+** excellent. Same Nadi (0/8) and Bhakoot dosha (0/7) are treated seriously but have classical **cancellations**, such as the same Moon-sign lord or different nakshatras.' },
      { type: 'h', text: 'South Indian poruthams' },
      { type: 'p', text: 'Dina, Gana, Mahendra, Stree Deergha, Yoni, Rasi, Rasi Adhipathi, Vashya, **Rajju** and **Vedha**. Rajju (the same body-part group of nakshatras) and Vedha (mutually obstructing stars) are considered critical in Tamil and Kerala traditions.' },
      { type: 'h', text: 'Beyond the Moon' },
      { type: 'list', items: [
        '**Mangal dosha on both sides or neither** is considered matched.',
        '**Cross 7th links**: one partner’s 7th sign equals the other’s lagna or Moon sign.',
        '**Venus–Mars chemistry**: his Mars harmonising with her Venus, and vice versa.',
        '**Dasha sandhi**: avoid marrying at the junction of a partner’s mahadashas.',
      ] },
      { type: 'example', title: 'Worked example: identical Moons score 28', text: [
        'Two people with the Moon in the same nakshatra and pada: Varna 1, Vashya 2, Tara 3, Yoni 4, Maitri 5, Gana 6, Bhakoot 7 (same sign counts as 1/1), but **Nadi 0**, because the same nakshatra always shares a nadi.',
        'Total **28/36**, “very good”, yet with Nadi dosha that no cancellation removes, because the pada is also the same. This shows why the total alone is never enough; always read the doshas.',
      ] },
      { type: 'try', text: 'Use **Match** in the top navigation to compare two charts with every koota, porutham and dosha explained.' },
    ],
    quiz: [
      { q: 'The highest-weighted koota is…', options: ['Bhakoot', 'Gana', 'Nadi', 'Yoni'], answer: 2, explain: 'Nadi carries 8 points.' },
      { q: 'Moon signs 6/8 from each other cause…', options: ['Nadi dosha', 'Bhakoot dosha', 'Gana dosha', 'No dosha'], answer: 1, explain: '2/12, 5/9 and 6/8 are the Bhakoot doshas.' },
    ],
  },
  {
    slug: 'vedic-synthesis', level: 'Vedic', module: 'Applied Jyotish',
    title: 'Reading a whole kundali: Gandhi’s chart',
    summary: 'Putting everything together, step by step, on one of the most studied charts in Jyotish.',
    minutes: 15,
    blocks: [
      { type: 'p', text: 'A full reading follows a fixed order, so that nothing is missed and nothing is over-weighted.' },
      { type: 'list', items: [
        '1. Lagna, lagna lord and planets in the 1st',
        '2. Moon sign, nakshatra and the Moon’s strength',
        '3. Functional benefics and malefics for this lagna; the yogakaraka',
        '4. Strong and weak planets (dignity, dig bala, vargottama)',
        '5. Yogas and doshas',
        '6. House-by-house via lords (Bhavat Bhavam)',
        '7. D9 confirmation, then the relevant vargas (D10 career, D7 children…)',
        '8. Dasha sequence → life chapters; transits → triggers',
      ] },
      { type: 'example', title: 'Step 1–2: self and mind', text: [
        '**Tula lagna** with **Venus (own sign), Mercury and Mars** in the 1st. Balance and justice (Libra), refined values (Venus), articulate (Mercury), fighting spirit (Mars). A **Malavya yoga** from Venus.',
        '**Moon in its own sign Karka (Cancer)** in the **10th house**, in Ashlesha. A strong, public, nurturing mind: the “mother of the nation” quality in the house of karma.',
      ] },
      { type: 'example', title: 'Step 3–5: power points', text: [
        '**Saturn is the yogakaraka** for Libra lagna, sitting in the 2nd (speech, values): austerity and truthful speech as tools.',
        '**Jupiter in the 7th** aspects the lagna: public life and partnerships guided by dharma. It also sits in the 10th from the Moon, forming **Gajakesari**.',
        '**Raja yogas**: lagna lord Venus with 9th lord Mercury in the 1st (self aligned with dharma). **Rahu in the 10th** with the Moon gives mass appeal and an unconventional, world-changing career.',
      ] },
      { type: 'example', title: 'Step 8: life chapters by dasha', text: [
        'Astro Life computes his Venus mahadasha from 1879 to 1899, covering his study in London and years in South Africa. Venus as lagna lord in its own sign made this a period of self-formation and first public stands.',
        'The Sun (1899–1905), Moon (1905–1915) and Mars (1915–1922) periods followed. **Mars** is the 2nd and 7th lord in the lagna, and his Indian mass movements began in this period.',
      ] },
      { type: 'callout', tone: 'note', text: 'Historical case studies illustrate technique through hindsight. They are not proof. The value is in learning to see how rules combine.' },
    ],
    quiz: [
      { q: 'What should come first in a full reading?', options: ['Dasha', 'Transits', 'Lagna and its lord', 'Nakshatra of Sun'], answer: 2, explain: 'Always begin with the lagna, the foundation of the chart.' },
    ],
  },
]
