import type { Lesson } from './types'

export const VEDIC: Lesson[] = [
  {
    slug: 'vedic-intro',
    level: 'Vedic',
    title: 'Jyotish basics: sidereal zodiac, lagna and the kundali',
    summary: 'How Vedic astrology differs from Western, and how to read North and South Indian charts.',
    minutes: 10,
    blocks: [
      { type: 'p', text: '**Jyotish** (“science of light”) is the traditional astrology of India, codified in texts such as *Brihat Parashara Hora Shastra* (BPHS). It shares planets and signs with Western astrology but differs in three important ways.' },
      { type: 'list', items: [
        '**Sidereal zodiac**: signs are aligned with the stars, not the seasons. The difference, the **ayanamsa**, is about 24° today, so most people’s Vedic signs are one sign “back” from their Western ones.',
        '**Lagna and Moon first**: the ascendant (lagna) and Moon sign (rashi) matter more than the Sun sign. In India, “What is your rashi?” means your Moon sign.',
        '**Whole-sign houses and timing**: each sign is one house (bhava), and a detailed timing system (dashas) says *when* the chart’s promises unfold.',
      ] },
      { type: 'h', text: 'Reading a North Indian chart' },
      { type: 'p', text: 'The North Indian chart is a square divided into diamonds and triangles. The **houses are fixed**: the top central diamond is always the 1st house (lagna), and houses run **counter-clockwise**. The small numbers are **sign numbers** (1 = Aries/Mesha … 12 = Pisces/Meena), so you find the signs by reading the numbers.' },
      { type: 'h', text: 'Reading a South Indian chart' },
      { type: 'p', text: 'The South Indian chart is a 4×4 grid in which the **signs are fixed**: Pisces top-left, then Aries, Taurus, Gemini across the top, running **clockwise**. The lagna is marked with a diagonal line, and you count houses clockwise from it.' },
      { type: 'example', title: 'Example: the same chart in both styles', text: [
        'Einstein has **Mithuna (Gemini) lagna**. In North Indian style the top diamond shows the number 3 (Gemini), with the Sun, Mercury, Venus and Saturn in the right-hand diamond: the 10th house, sign 12 (Pisces).',
        'In South Indian style, the Gemini box (top-right) carries the lagna mark, and the same four planets sit in the Pisces box (top-left). Counting clockwise from Gemini, Pisces is the 10th house.',
        'Same chart, two drawings. Use the style toggle on your kundali to compare them.',
      ] },
      { type: 'table', headers: ['#', 'Sign', 'Sanskrit', 'Lord'], rows: [
        ['1', 'Aries', 'Mesha', 'Mars'], ['2', 'Taurus', 'Vrishabha', 'Venus'], ['3', 'Gemini', 'Mithuna', 'Mercury'],
        ['4', 'Cancer', 'Karka', 'Moon'], ['5', 'Leo', 'Simha', 'Sun'], ['6', 'Virgo', 'Kanya', 'Mercury'],
        ['7', 'Libra', 'Tula', 'Venus'], ['8', 'Scorpio', 'Vrishchika', 'Mars'], ['9', 'Sagittarius', 'Dhanu', 'Jupiter'],
        ['10', 'Capricorn', 'Makara', 'Saturn'], ['11', 'Aquarius', 'Kumbha', 'Saturn'], ['12', 'Pisces', 'Meena', 'Jupiter'],
      ] },
      { type: 'callout', tone: 'note', text: 'Astro Life uses the **Lahiri (Chitrapaksha)** ayanamsa, the Indian government standard, together with whole-sign houses and mean nodes.' },
      { type: 'try', text: 'Open your chart in Vedic mode and switch between North and South Indian styles. Find your lagna in both.' },
    ],
    quiz: [
      { q: 'In a North Indian chart, what is fixed?', options: ['The signs', 'The houses', 'The planets', 'Nothing'], answer: 1, explain: 'The top diamond is always the 1st house; sign numbers rotate.' },
      { q: 'In India, “your rashi” usually means…', options: ['Sun sign', 'Moon sign', 'Lagna', 'Nakshatra'], answer: 1, explain: 'Rashi refers to the Moon’s sign.' },
    ],
  },
  {
    slug: 'vedic-grahas-bhavas',
    level: 'Vedic',
    title: 'Grahas, bhavas and house lords',
    summary: 'The nine grahas, the twelve bhavas and the core Parashari technique: follow the house lord.',
    minutes: 12,
    blocks: [
      { type: 'p', text: 'Jyotish uses **nine grahas**: the Sun, Moon, Mars, Mercury, Jupiter, Venus and Saturn, plus the lunar nodes **Rahu** and **Ketu**. Uranus, Neptune and Pluto are not used traditionally.' },
      { type: 'table', headers: ['Graha', 'Nature', 'Signifies (karaka)', 'Exalted', 'Debilitated'], rows: [
        ['Surya (Sun)', 'Mild malefic', 'Soul, father, authority', 'Aries 10°', 'Libra 10°'],
        ['Chandra (Moon)', 'Benefic', 'Mind, mother, emotions', 'Taurus 3°', 'Scorpio 3°'],
        ['Mangala (Mars)', 'Malefic', 'Energy, siblings, land', 'Capricorn 28°', 'Cancer 28°'],
        ['Budha (Mercury)', 'Benefic', 'Intellect, speech, trade', 'Virgo 15°', 'Pisces 15°'],
        ['Guru (Jupiter)', 'Great benefic', 'Wisdom, children, fortune', 'Cancer 5°', 'Capricorn 5°'],
        ['Shukra (Venus)', 'Benefic', 'Spouse, love, luxury', 'Pisces 27°', 'Virgo 27°'],
        ['Shani (Saturn)', 'Great malefic', 'Discipline, delay, longevity', 'Libra 20°', 'Aries 20°'],
        ['Rahu', 'Malefic', 'Ambition, foreign, obsession', '—', '—'],
        ['Ketu', 'Malefic', 'Detachment, moksha', '—', '—'],
      ] },
      { type: 'h', text: 'House groups' },
      { type: 'list', items: [
        '**Kendras** (1, 4, 7, 10): pillars of the chart. They give strength and visibility.',
        '**Trikonas** (1, 5, 9): houses of fortune and dharma, the most auspicious.',
        '**Dusthanas** (6, 8, 12): houses of difficulty, such as disease, crisis and loss.',
        '**Upachayas** (3, 6, 10, 11): houses of growth. Malefics actually do well here.',
      ] },
      { type: 'h', text: 'The house-lord technique' },
      { type: 'p', text: 'Every house is ruled by the lord of its sign. **Where that lord goes, the house’s matters go.** A lord placed in a kendra or trikona supports its house; a lord in a dusthana brings obstacles to it, unless the lord itself rules a dusthana (the **viparita** principle, where bad cancels bad).' },
      { type: 'example', title: 'Deep example: Einstein’s 10th and 9th lords', text: [
        'Gemini lagna makes **Pisces the 10th house** (career), ruled by **Jupiter**. Jupiter sits in Aquarius in the **9th house** (higher learning, dharma, teachers): the career is expressed through higher knowledge and philosophy.',
        'Meanwhile the **9th lord Saturn** sits in Pisces in the **10th house**: fortune and learning are poured into the career. Each planet is in the other’s sign, a **parivartana (exchange)** between the 9th and 10th lords, which is a famous **Dharma–Karma Raja Yoga**.',
        'Rule chain: 10th lord in 9th + 9th lord in 10th → exchange of kendra and trikona lords → Raja Yoga → recognition through one’s life’s work.',
      ] },
      { type: 'try', text: 'Open the **Bhavas** tab on your chart. Where does your 10th lord sit? That is where your career energy flows.' },
    ],
    quiz: [
      { q: 'Which houses are dusthanas?', options: ['1, 5, 9', '1, 4, 7, 10', '6, 8, 12', '3, 6, 10, 11'], answer: 2, explain: 'Dusthanas are the houses of difficulty.' },
      { q: 'A natural malefic in the 11th house is usually…', options: ['Very harmful', 'Good, since the 11th is an upachaya house', 'Irrelevant', 'Always debilitated'], answer: 1, explain: 'Malefics give drive and gains in upachaya houses.' },
    ],
  },
  {
    slug: 'vedic-nakshatras',
    level: 'Vedic',
    title: 'The 27 nakshatras',
    summary: 'Lunar mansions of 13°20′, their rulers, and why your birth star matters.',
    minutes: 9,
    blocks: [
      { type: 'p', text: 'The zodiac is divided into **27 nakshatras** (lunar mansions) of 13°20′ each, roughly the distance the Moon travels in a day. Each is split into four **padas** (quarters) of 3°20′.' },
      { type: 'p', text: 'Your **janma nakshatra** is the one holding your Moon. It is used for naming ceremonies, compatibility (the ashtakoota score), muhurta (auspicious timing) and, most importantly, the **Vimshottari dasha**.' },
      { type: 'table', headers: ['Nakshatra lord', 'Nakshatras (1st, 2nd, 3rd cycle)'], rows: [
        ['Ketu', 'Ashwini, Magha, Mula'], ['Venus', 'Bharani, Purva Phalguni, Purva Ashadha'], ['Sun', 'Krittika, Uttara Phalguni, Uttara Ashadha'],
        ['Moon', 'Rohini, Hasta, Shravana'], ['Mars', 'Mrigashira, Chitra, Dhanishta'], ['Rahu', 'Ardra, Swati, Shatabhisha'],
        ['Jupiter', 'Punarvasu, Vishakha, Purva Bhadrapada'], ['Saturn', 'Pushya, Anuradha, Uttara Bhadrapada'], ['Mercury', 'Ashlesha, Jyeshtha, Revati'],
      ] },
      { type: 'example', title: 'Example: Jyeshtha Moon', text: [
        'Einstein’s Moon is at 22°21′ Scorpio, in **Jyeshtha** (“the eldest”), ruled by **Mercury**, with deity Indra.',
        'Jyeshtha gives a protective, responsible, intellectually powerful nature, and its Mercury rulership adds an analytical mind.',
        'Because Mercury rules his birth star, his life began in the **Mercury mahadasha**.',
      ] },
    ],
    quiz: [
      { q: 'How wide is one nakshatra?', options: ['10°', '13°20′', '15°', '30°'], answer: 1, explain: '360° ÷ 27 = 13°20′.' },
    ],
  },
  {
    slug: 'vedic-yogas',
    level: 'Vedic',
    title: 'Yogas and doshas',
    summary: 'Classical planetary combinations: Raja, Dhana, Gajakesari, Mahapurusha, and the doshas.',
    minutes: 12,
    blocks: [
      { type: 'p', text: 'A **yoga** is a specific combination with a classical result. Yogas are the clearest example of Jyotish’s rule-based nature: each has an exact condition you can check.' },
      { type: 'table', headers: ['Yoga', 'Rule', 'Result'], rows: [
        ['Raja Yoga', 'Kendra lord + trikona lord conjunct or exchanged', 'Status, success, authority'],
        ['Dhana Yoga', '2nd/11th lord with 1st/5th/9th lord', 'Wealth'],
        ['Gajakesari', 'Jupiter in a kendra from the Moon', 'Wisdom, reputation'],
        ['Budhaditya', 'Sun + Mercury in one sign', 'Intelligence'],
        ['Pancha Mahapurusha', 'Mars/Mercury/Jupiter/Venus/Saturn in own or exaltation sign in a kendra', 'Ruchaka, Bhadra, Hamsa, Malavya, Shasha: a “great person”'],
        ['Viparita Raja', 'Lord of 6/8/12 in another dusthana', 'Success through adversity'],
        ['Neecha Bhanga', 'Debilitated planet’s lord in a kendra (one of several rules)', 'Weakness turns to strength'],
        ['Kemadruma', 'No planets 2nd or 12th from the Moon', 'Loneliness or instability, often cancelled'],
      ] },
      { type: 'h', text: 'Strength matters' },
      { type: 'p', text: 'A yoga is only as strong as its planets. A Raja Yoga made by debilitated or combust planets gives modest results; one made by exalted planets in kendras can be life-defining. Yogas mainly deliver during the **dashas** of the planets that form them.' },
      { type: 'h', text: 'Doshas, gently' },
      { type: 'p', text: '**Mangal dosha** (Mars in the 1st, 2nd, 4th, 7th, 8th or 12th) and **Kaal Sarp** (all planets on one side of the nodes) are widely discussed. Mangal dosha affects a large share of all charts and has many cancellation rules, and Kaal Sarp does not appear in BPHS. Treat them as themes to understand, not reasons for fear.' },
      { type: 'example', title: 'Deep example: Malavya Yoga', text: [
        'Einstein’s **Venus is exalted in Pisces in the 10th house**, a kendra. That meets the rule for **Malavya Yoga**, one of the five Mahapurusha yogas.',
        'Classically Malavya gives refinement, artistic sensitivity and charm. Einstein was a devoted violinist who said that if he were not a physicist he would probably be a musician. Hindsight readings are illustrations, not proof, but they show how a rule maps to a life.',
      ] },
    ],
    quiz: [
      { q: 'Hamsa Yoga is formed by which planet?', options: ['Mars', 'Venus', 'Jupiter', 'Saturn'], answer: 2, explain: 'Jupiter strong in a kendra forms Hamsa.' },
    ],
  },
  {
    slug: 'vedic-vargas',
    level: 'Vedic',
    title: 'Divisional charts (D1–D10)',
    summary: 'How each sign is subdivided into vargas, and what each chart says about a life area.',
    minutes: 14,
    blocks: [
      { type: 'p', text: 'A **varga** divides each 30° sign into equal parts and maps each part to a sign. The result is a new chart that zooms in on one area of life. The rule: **D1 shows the promise; the varga shows how it unfolds**. A divisional chart cannot deliver what D1 denies.' },
      { type: 'table', headers: ['Chart', 'Division', 'Rule for mapping', 'Life area'], rows: [
        ['D1 Rashi', '30°', 'The sign itself', 'Everything'],
        ['D2 Hora', '15°', 'Odd signs: Leo then Cancer; even signs: Cancer then Leo', 'Wealth'],
        ['D3 Drekkana', '10°', 'Same sign, 5th, 9th', 'Siblings, courage'],
        ['D4 Chaturthamsa', '7°30′', 'Same sign, 4th, 7th, 10th', 'Home, property'],
        ['D5 Panchamsa*', '6°', 'Odd: Ar, Aq, Sg, Ge, Li; even: Ta, Vi, Pi, Cp, Sc', 'Fame, power'],
        ['D6 Shashthamsa*', '5°', 'Odd from Aries, even from Libra', 'Health, struggles'],
        ['D7 Saptamsa', '4°17′', 'Odd from itself, even from the 7th', 'Children'],
        ['D8 Ashtamsa*', '3°45′', 'Movable from Ar, fixed from Sg, dual from Le', 'Sudden events'],
        ['D9 Navamsa', '3°20′', 'Movable from itself, fixed from 9th, dual from 5th', 'Marriage, dharma, strength'],
        ['D10 Dasamsa', '3°', 'Odd from itself, even from the 9th', 'Career'],
      ] },
      { type: 'callout', tone: 'warn', text: '*D5, D6 and D8 are not among Parashara’s sixteen vargas. They come from later traditions and vary between schools, so give them less weight.' },
      { type: 'h', text: 'Reading a varga, step by step' },
      { type: 'list', items: [
        '1. Note the **varga lagna** and where its lord sits in that varga.',
        '2. Examine the **key house** (10th in D10, 7th in D9, 5th in D7, 4th in D4): its lord’s house and dignity, and any occupants.',
        '3. Check the **karaka** (the Sun and Saturn for career, Venus for marriage, Jupiter for children).',
        '4. List planets **strong** (own or exalted) or **weak** (debilitated) in that varga. Their dashas deliver accordingly.',
        '5. **Vargottama**: a planet in the same sign in D1 and D9 is exceptionally strong.',
      ] },
      { type: 'example', title: 'Worked example: calculating a Navamsa', text: [
        'Mars at **4°44′ Capricorn**. Capricorn is a movable sign, so its navamsas start from Capricorn itself.',
        '4°44′ ÷ 3°20′ = 1.42, which falls in the 2nd navamsa, so we count 2 signs from Capricorn: **Aquarius**.',
        'Shortcut: navamsa sign = floor(sidereal longitude × 9 ÷ 30) mod 12, counted from Aries. Mars at 274.73° gives floor(82.4) = 82, and 82 mod 12 = 10, which is Aquarius (counting Aries as 0).',
      ] },
      { type: 'example', title: 'Worked example: calculating a Dasamsa', text: [
        'Venus at **24°48′ Pisces**. Pisces is an even sign, so the count starts from the 9th sign from Pisces, which is **Scorpio**.',
        '24°48′ ÷ 3° = 8.27, which is the 9th part, so we count 9 signs from Scorpio: Scorpio, Sagittarius, Capricorn, Aquarius, Pisces, Aries, Taurus, Gemini, **Cancer**.',
      ] },
      { type: 'callout', tone: 'tip', text: 'Divisional charts are very sensitive to birth time: the D10 lagna changes every ~12 minutes and the D9 lagna every ~13. Be cautious with vargas if your birth time is approximate.' },
      { type: 'try', text: 'Open the **D1–D10 Charts** tab. Pick D10 and compare its 10th lord with your D1 10th lord.' },
    ],
    quiz: [
      { q: 'Which divisional chart is used for career?', options: ['D7', 'D9', 'D10', 'D4'], answer: 2, explain: 'The Dasamsa (D10) refines the 10th house.' },
      { q: 'A planet in the same sign in D1 and D9 is called…', options: ['Combust', 'Vargottama', 'Retrograde', 'Neecha'], answer: 1, explain: 'Vargottama planets are especially strong.' },
    ],
  },
  {
    slug: 'vedic-dashas',
    level: 'Vedic',
    title: 'Vimshottari dasha and Sade Sati',
    summary: 'The 120-year planetary period system that times events, plus Saturn’s famous transit.',
    minutes: 11,
    blocks: [
      { type: 'p', text: 'The **Vimshottari dasha** divides life into planetary periods totalling 120 years. The sequence is always: Ketu 7, Venus 20, Sun 6, Moon 10, Mars 7, Rahu 18, Jupiter 16, Saturn 19, Mercury 17 years.' },
      { type: 'h', text: 'Where it starts' },
      { type: 'p', text: 'Your first **mahadasha** (major period) belongs to the lord of your Moon’s nakshatra. How far the Moon had travelled through that nakshatra decides how much of the first period had already elapsed before birth.' },
      { type: 'example', title: 'Worked example: dasha balance', text: [
        'Moon at 22°21′ Scorpio = 232.35° sidereal. Jyeshtha spans 226°40′–240°00′, so the Moon has covered 5.68° of 13.33°, or **42.6%**.',
        'Jyeshtha is ruled by Mercury (17 years), so the balance of the Mercury dasha at birth = 57.4% × 17 = **9.8 years**. Then follow Ketu (7), Venus (20), Sun (6) and so on.',
      ] },
      { type: 'h', text: 'Interpreting a dasha' },
      { type: 'list', items: [
        'The dasha lord gives results of the **houses it occupies and rules**, coloured by its **dignity** and **yogas**.',
        '**Antardashas** (sub-periods) within a mahadasha refine timing: the Jupiter–Venus period combines both planets’ themes.',
        'Check the dasha lord in the **relevant varga**: a strong Saturn in D10 gives career growth in Saturn’s period.',
      ] },
      { type: 'h', text: 'Sade Sati' },
      { type: 'p', text: 'When transiting Saturn moves through the 12th, 1st and 2nd signs from your natal Moon (about 7½ years), it is called **Sade Sati**. It is a period of pressure, responsibility and restructuring, often followed by lasting maturity and achievement. It recurs about every 30 years.' },
      { type: 'callout', tone: 'note', text: 'Dasha boundaries depend on the Moon’s exact degree and the year length used, so different software may differ by a few weeks.' },
    ],
    quiz: [
      { q: 'How long is the full Vimshottari cycle?', options: ['84 years', '108 years', '120 years', '144 years'], answer: 2, explain: 'Vimshottari literally means “120”.' },
      { q: 'The first mahadasha is ruled by…', options: ['The lagna lord', 'The Moon’s nakshatra lord', 'The Sun sign lord', 'Jupiter always'], answer: 1, explain: 'It starts from the lord of the janma nakshatra.' },
    ],
  },
]
